### ISSUE TITLE
Data stuffing

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-ppm/draft-ietf-ppm-dap#20]
To what extent should the system detect or mitigate fake clients from stuffing data into the system? We could so far as to say that all data must come from an authenticated client. (Maybe there's something with anonymous credentials we can do here?) We might also recommend simple mitigations, such as checking for repeated entries from the "same client" (same IP, same application-layer identifier, etc) during a batch.

**Comment by cjpatton** [comment]
In today's design call we discussed mitigating this issue using an "ingestion server" that sits in front of the leader. In practice, the leader and ingestor might be the same entity.

**Comment by cjpatton** [comment]
@csharrison, this issue tracks the "double counting" problem we discussed today.

**Comment by csharrison** [comment]
For our use-case, we'd likely want an application-layer identifier to impose limits on clients or even batches of clients (to make this kind of input tracking scale a bit better).

We are also interested in allowing clients to input the same piece of data multiple times, up to some fixed number. This is to support the batch querying model where a server has a collection of records and would like to learn e.g. both daily aggregates and weekly aggregates, which would require every piece of data getting processed twice.

**Comment by divergentdave** [comment]
This is addressed in the newly rewritten security considerations, under [section 7.2, Sybil attacks](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-sybil-attacks).
