### ISSUE TITLE
Aggregation set agreement underspecified

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#218]
It seems to me we are not entirely clear on how aggregators determine which set of reports to aggregate over.

The spec currently uses a checksum to verify that the sets are the same but isn't very specific about how the set is defined. If I understand correctly this is done using the `batch_interval` argument which only supports time as a selection parameter.

I see a few issues here:
1. We should define how aggregators agree on a set in case the checksum fails.
2. `batch_interval` should probably be a `batch_filter` so it can also depend on version information, location, etc. (Of course it is difficult to define which information can be metadata and how much of a privacy concern it creates.) See #27 .
3. `batch_filter` would have to be part of the `CollectReq` to support the drill-down feature discussed in other issues, e.g. #183 .

**Comment by cjpatton** [comment]
Hi Simon!

> 1. We should define how aggregators agree on a set in case the checksum fails.
Right now we treat this case as a fatal error. Doing more than can get complicated. For example, one could imagine a scheme whereby the aggregators try to determine the union of their two sets and exclude reports not in the union. 

Before we get into attempting to recover data, I think we should first try to get a sense of how likely this error is to occur in a typical deployment.

> 2. `batch_interval` should probably be a `batch_filter` so it can also depend on version information, location, etc. (Of course it is difficult to define which information can be metadata and how much of a privacy concern it creates.) See #27 .
> 3. `batch_filter` would have to be part of the `CollectReq` to support the drill-down feature discussed in other issues, e.g. #183 .

We definitely want to support this feature, however I think solving #195 would be a prerequisite.
