### ISSUE TITLE
Usage of HPKE `info` and `aad` fields (was "HPKE: do not use both application_info & AAD.")

### ISSUE THREAD

**Issue by BranLwyd** [ietf-wg-ppm/draft-ietf-ppm-dap#221]
Per https://www.rfc-editor.org/rfc/rfc9180.pdf section 8.1:
> Applications that only use the single-shot APIs described in Section 6 should use the Setup info parameter for specifying auxiliary authenticated information. Implementations which only expose single-shot APIs should not allow applications to use both Setup info and Context aad or exporter_context auxiliary information parameters.

PPM effectively uses the single-shot APIs; we should consider refactoring PPM's usage of HPKE to use only one of application_info & AAD. Following the advice of the HPKE RFC, we would want to use application_info.

This would permit slightly simpler implementations. I am not sure how much it would simplify the HPKE computations.

**Comment by tgeoghegan** [comment]
Should we then formally use the single shot HPKE APIs from [HPKE section 6.1](https://www.rfc-editor.org/rfc/rfc9180#name-encryption-and-decryption-2)?

**Comment by BranLwyd** [comment]
That would be my recommendation (though, somewhat confusingly given the advice quoted above, those APIs still allow specifying both application info & AAD).

Implementations can & do already use the single-shot APIs, so I strongly suspect specifying the single-shot APIs will be feasible. [See https://github.com/divviup/janus/blob/8ad7d31b3bded508ed31e65ee8782088fdfe719c/janus_server/src/hpke.rs#L197 & https://github.com/divviup/janus/blob/8ad7d31b3bded508ed31e65ee8782088fdfe719c/janus_server/src/hpke.rs#L306.]

**Comment by BranLwyd** [comment]
The reasoning is:
a) it follows the advice of the HPKE spec (quoted above)
b) AFAICT, in a single-shot setting, application info & AAD serve exactly the same purpose, so using both is arbitrary/confusing/a potential source of mistakes. (in a multi-shot setting, application info is bound to all encryptions/decryptions done by the same context; AAD is bound to a single encryption/decryption)

**Comment by cjpatton** [comment]
TBH I'm not sure I agree with the quoted guidance here. There is a concept in protocol design known as "domain separation", the goal of which is to provide some kind of binding of long-term secret key operations to the context in which they were used. Imagine, for example, that someone used an HPKE secret key for PPM and some other protocol. Suppose further that both are using the empty string for `info`. Then the security of our PPM deployment depends on how the other protocol uses the derived AEAD key, since in both protocols we may end up deriving the same AEAD key. One way to avoid creating this attack surface is to pick an `info` string that no other application is likely to choose so that derived keys are guaranteed to not collide (except with some negligible probability).

That said, I'd go for changing how we use `info` and `aad`. Something like this might be simpler:
* Let `info` be a fixed string that identifies the protocol (e.g., "ppm-00").
* Let `aad` encode the task ID, sender/receiver roles, etc.

**Comment by BranLwyd** [comment]
I definitely agree that application info should include information allowing domain separation, for the reasons you mention. (Indeed, the current PPM spec includes the strings "ppm input share" or "ppm aggregate share" in its application infos, presumably for this purpose.)

But I think that's orthogonal to the question of whether we should also use AAD, since the application info could also include information other than the "domain separation parameter". Picking one example to make things concrete, a client upload request sets its application info to `Report.task_id || "ppm input share" || 0x01 || server_role` and its AAD to `Report.nonce || Report.extensions`. But it could just as easily set the application info to `Report.task_id || "ppm input share" || 0x01 || server_role || Report.nonce || Report.extensions` and not use AAD. (Or alternatively, it could place that string in the AAD and not use application info.)

My argument is that it's simpler to use one of the parameters, since in the single-shot setting that PPM is using HPKE, the two parameters serve exactly the same purpose (i.e. including additionally-authenticated data).

**Comment by cjpatton** [comment]
As I see it, our goal is to make sure that decryption only succeeds if the sender and receiver agree on the "context", i.e., the task ID, sender/receiver role, nonce, extensions, and so on. This way a MITM cannot force the aggregator to interpret an input share incorrectly. Does this sound reasonable to you?

From the point of view of this threat model, I don't think it's immediately clear that sticking the context in `info` or `aad` is equivalent. For example, if we stuff the context in `info`, then it influences the derivation of the AEAD key; but depending on the AEAD, it might be feasible for an attacker to find a find two keys that decrypt the same ciphertext. (See https://eprint.iacr.org/2020/1153.pdf.) More analysis will be needed to say for sure whether this weakness in the AEAD amounts to an attack against our protocol. In the meantime, sticking the "context" in `aad` seems like a more conservative choice to me.

**Comment by BranLwyd** [comment]
Given your concern, your approach SGTM. It sounds like this may be a concern worth raising with the folks working on the HPKE spec, given the advice to "use the Setup info parameter for specifying auxiliary authenticated information", but I'm not going to chase this down currently.

**Comment by cjpatton** [comment]
So I think there's two tasks for this issue:
* Move task ID from `info` to `aad`
* Use single-shot APIs for HPKE

Anything else?

**Comment by BranLwyd** [comment]
(reopening for now as the fix PR has been reverted temporarily)
