### ISSUE TITLE
Decide which Task parameters might be mutable.

### ISSUE THREAD

**Issue by branlwyd** [ietf-wg-ppm/draft-ietf-ppm-dap#237]
Tasks are defined with a number of parameters; eventually, it might be helpful to determine which might be mutated (and any restrictions on how they might be mutated).

One initial thought is that any of the parameters that end up distributed to clients are likely effectively immutable, if only due to the challenge of updating all of the clients.

[This fell out of a discussion on https://github.com/divviup/janus/pull/142.]

**Comment by cjpatton** [comment]
I think for the time being we should plan on the all of the parameters of a config being immutable: If you need to change them role a new task.

**Comment by cjpatton** [comment]
@branlwyd for now we might just note that the collector config and the verification key might change over the course of a task's lifetime, but this is deployment specific. Everything else should be immutable.

**Comment by tgeoghegan** [comment]
I believe that VDAF-05's requirement that the VDAF verify key be set in all aggregators before any reports are prepared (https://mailarchive.ietf.org/arch/msg/ppm/h4ArBZTQ1H_dm0umwjT-gcXaBHg/) means that you can't rotate the VDAF verify key without making a new task. That leaves the collector HPKE config, but there again I think making a new task suffices, given that collector HPKE configs can likely be safely used for quite a long time.

For DAP-05, I think we should check if there's any language in the draft that suggests task parameters are immutable, and add a sentence as needed explicitly stating that they're immutable.
