### ISSUE TITLE
Provide error handling guidance

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#239]
The draft defines a list of problem document types to represent conditions such as an aggregate share request being rejected because it would violate privacy requirements. Some of these are fatal but in some cases, the sender of a request can try again. For instance, if a `CollectReq` is rejected because its `batch_interval` does not contain enough reports, then the collector could either wait a while for more reports to arrive or try again immediately with a bigger `batch_interval`. We should add guidance on which errors are non-fatal and what implementations can try to do when they encounter them.

**Comment by tgeoghegan** [comment]
Some discussion [here](https://github.com/ietf-wg-ppm/ppm-specification/pull/233#discussion_r861403548).

**Comment by simon-friedberger** [comment]
We should also remove 'reportRejected': "Report could not be processed for an unspecified reason." and replace it with something clearer. In Janus it is currently used for expired task, expired reports, repeated report ID and already collected batches.
* Expired task → Client configuration error, should be updated.
* Expired report → Client configuration error, maybe invalid clock. Probably not fixable.
* Repeated report ID → Maybe a network issue. Report should be considered as sent. Probably fine.
* Already collected batch → Mismatch between Client and Collector behavior is causing data loss.

**Comment by branlwyd** [comment]
regarding `reportRejected`: I definitely don't object to adding more-specific error codes where it makes sense (though I'd lean towards adding codes only when the receiver of the error might make a logic decision based on the code). But I think we should also keep something as generic as `reportRejected`, as an aggregator is allowed to reject any report for any implementation-specific reason it chooses -- it'd be good to have a catchall error for this kind of rejection.
