### ISSUE TITLE
No negotiation for HPKE Configs

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#248]
The server only supplies one config, so what happens if the server would support X22519 and P-256? We can fix this by having the server supply multiple configs.

**Comment by cjpatton** [comment]
This is probably a good idea. We could just change the payload of the response to `GET /hpke_config` to a sequence of `HpkeConfig` messages rather than one.

**Comment by cjpatton** [comment]
As mentioned in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/303#discussion_r954175414, it might be useful to allow the client to advertise which algorithms it supports. This would increase the likelihood of successfully negotiating an a HPKE suite that both parties support.

**Comment by cjpatton** [comment]
@ekr should we try to tackle this in DAP-03?
