### ISSUE TITLE
Consider specifying aggregator behavior on message-deserialization failures.

### ISSUE THREAD

**Issue by branlwyd** [ietf-wg-ppm/draft-ietf-ppm-dap#255]
The DAP specification defines a number of error modes, which ultimately end up mapped to error codes defined in section 3.1.

Currently, the specified behavior does not describe how to treat message-deserialization failures, in any of client-aggregator, aggregator-aggregator, or collector-aggregator communications. We should consider specifying this.

Initial thoughts:
* Moving to `FAILED` (with a new error code?) or `INVALID` makes sense to me, for deserialization errors during the aggregation process.
* It'd be very nice if one "bad" client report didn't fail the entire aggregation job, e.g. we should probably specify behavior that limits the "blast radius" of a badly-serialized message.
* We could leave this unspecified; I suppose the risk is that different implementations might treat this error mode with different semantics (e.g. some will fail a single report, some will fail the entirety of the aggregation job).

**Comment by BranLwyd** [comment]
(This fell out of discussion on https://github.com/divviup/janus/pull/167; FWIW, Janus will currently transition a report aggregation to `INVALID` if it fails to decode a message, though of course that's just one implementation's choice.)
