### ISSUE TITLE
Checking `batch-collected` at time of aggregate initalization is insufficient

### ISSUE THREAD

**Issue by divergentdave** [ietf-wg-ppm/draft-ietf-ppm-dap#259]
I think that there is a hole in our anti-replay requirements, for tasks with `max_batch_lifetime > 1`. The issue is that currently, we only require that aggregators check if reports fall in intervals that have already been collected during the leader and helper aggregate initialization, see section `input-share-batch-validation`. We need a similar check either when handling aggregation continuations or the collect flow.

As an example of what we should be disallowing, consider a task with `min_batch_size = 10, max_batch_lifetime = 2`. Let's say that all aggregations are done with the same aggregation parameter, whatever it is.

- The leader sends out an AggregateInitializeReq for its first job, with ten reports.
  - The input share validation checks succeed, as there have been no collect reqeusts yet.
- The leader sends out an AggregateInitializeReq for its second job, with one report. This succeeds as well.
- The leader sends an AggregateContinueReq for its first job, with `finished` transitions.
- The leader sends an AggregateShareReq for an interval that covers all reports in both jobs.
- The leader sends an AggregateContinueReq for its second job, with `finished` transitions.
  - Note that we do not require the helper to do any checks against collect requests when handling aggregation continuations. (see `agg-continue-flow`)
- The leader sends a second AggregateShareReq, identical to the previous request.
  - Note that the checks in `batch-parameter-validation` pass.
    - The batch includes eleven reports, so `min_batch_size` is satisfied.
    - We assumed `max_batch_lifetime = 2`, and each report has been collected zero or one times thus far.
  - Aside from the `max_batch_lifetime` condition, the `collect-aggregate` section does not impose any other checks or conditions requiring the helper to consider previous AggregateShareReq requests when deciding if a request is valid, nor does it require that identical requests always get the same response.

After receiving the two aggregate shares produced above, the collector could compute the aggregate function over both the first ten reports and all eleven reports. For many functions, this would allow recovery of the eleventh input, breaking our privacy goal.

There is a paragraph that says:

> After issuing an aggregate-share request for a given batch interval, it is an error for the leader to issue any more aggregate or aggregate-init requests for additional reports in the batch interval. These reports will be rejected by helpers as described {{agg-init}}.

However, the referenced section only covers the "aggregate-init" part, and not aggregate continuation.

**Comment by cjpatton** [comment]
At IETF 118 I volunteered to implement multi-collection and resolve all related open issues.
