### ISSUE TITLE
Clarify the domain in which aggregation job IDs must be unique

### ISSUE THREAD

**Issue by BranLwyd** [ietf-wg-ppm/draft-ietf-ppm-dap#260]
The current DAP specification says (section 4.3.1.1):
```
Generate a fresh AggregationJobID. This ID MUST be unique within the context of the corresponding DAP task.
```
...which implies that the domain of uniqueness for aggregation job IDs is at least as large as all aggregation job IDs for the related task.

But then, the aggregate continue request definition is (section 4.3.2.1):
```
struct {
  AggregationJobID job_id;
  PrepareStep prepare_shares<1..2^16-1>;
} AggregateContinueReq;
```
... which implies that aggregation job IDs must be unique over all aggregation jobs (on any task), since the `task_id` is omitted.

Depending on intent, I suggest one of the following edits:
* Update section 4.3.1.1 to state that aggregation job IDs must be unique over all aggregation jobs (for any task the aggregator knows about).
* Update section 4.3.2.1 to include a `TaskId` in the `AggregateContinueReq` message.

**Comment by BranLwyd** [comment]
My two cents: I really like keeping separate tasks isolated as much as possible, so I like the idea of requiring aggregation job IDs to be unique only over the domain of aggregation jobs for the related task. OTOH, this would require sending extra bytes with every `AggregateContinueReq`, which folks certainly might find unpalatable.

**Comment by cjpatton** [comment]
I agree this needs to be fixed and I prefer your second suggestion.
