### ISSUE TITLE
Specify handling of agg_param

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#267]
There is an agg_param in AggregateInitializeReq and in CollectReq and in AggregateShareReq.
IIUC CollectReq.agg_param may need to be forwarded as AggregateInitializeReq.agg_param or - depending on the VDAF - later as AggregateShareReq.agg_param.

ISTM the logic needs to be specified to implement DAP correctly.

**Comment by cjpatton** [comment]
Yes, both the agg_param and batch_interval need to match. Is there anything that needs to change in order to make this so?

**Comment by simon-friedberger** [comment]
Well, if the agg_param in all three (CollectReq, AggregateInitializeReq, AggregateShareReq) must be the same the leader cannot start aggregating before the collector sends the request. Which is an optimization that was requested, right?

I think there are two valid scenarios:
1. AggregateInitializeReq.agg_param can be determined by the leader, e.g. because it is empty. In this case the leader can start aggregating ahead of time, without a request. Later AggregateShareReq.agg_param will be set to CollectReq.agg_param.
2. AggregateInitializeReq.agg_param does need information from the collector. So it is set to CollectReq.agg_param. Presumably AggregateShareReq.agg_param can then be empty.

**Comment by cjpatton** [comment]
> Well, if the agg_param in all three (CollectReq, AggregateInitializeReq, AggregateShareReq) must be the same the leader cannot start aggregating before the collector sends the request. Which is an optimization that was requested, right?
>
> I think there are two valid scenarios:
> 
>     1. AggregateInitializeReq.agg_param can be determined by the leader, e.g. because it is empty. In this case the leader can start aggregating ahead of time, without a request. Later AggregateShareReq.agg_param will be set to CollectReq.agg_param.
> 
>     2. AggregateInitializeReq.agg_param does need information from the collector. So it is set to CollectReq.agg_param. Presumably AggregateShareReq.agg_param can then be empty.

Right, these are the two valid scenarios. For (2.) the current use case is Prio3, where the agg_param is always "" and aggregation can begin prior to receiving a collect request. For (1.) the envisioned use case is Poplar1, where the agg parameter encodes a set of candidate prefixes. In general these cannot be known until the agg result for a previous Poplar1 evaluation has been collected.

**Comment by simon-friedberger** [comment]
So we need a flag in the Task to determine which scenario applies, right?

**Comment by cjpatton** [comment]
Unless this impacts interop, I don't think the spec needs normative text to address this. I think the text we have in the overview is sufficient.

**Comment by cjpatton** [comment]
Given no guidance on how to resolve this, and because it hasn't been touched in a while, I'm going to close this issue.
