### ISSUE TITLE
Consider supporting coarse-grained timestamp in Nonce

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#274]
Not sure if DAP enforces precision of `Nonce.Time`:

```
Time uint64; /* seconds elapsed since start of UNIX epoch */
```

But with fine-grained timestamp, it is easier for attacker to associate a report with the user sent that report. For example, if timestamp is accurate to second, and leader is compromised, attacker can compare users that uploaded at a given second (perhaps from a routing server) and reports' timestamp, then figure out if a particular user has contributed to a task. With a coarse-grained timestamp, however, we can minimise this threat with a secure routing server. Anti-replay can still be satisfied with the UUID part of Nonce.

**Comment by chris-wood** [comment]
This is a valid concern. One reasonable change would be to modify the report timestamp to align with the batch window start (min_batch_duration), and then bump the size of the nonce to offset the increase change of collisions. Specifically, this would mean we update the Nonce like so:

~~~
struct {
  Time time; // set to min_batch_duration for current batch window
  uint8 rand[32]; // or 16 bytes, whatever we're comfortable with for the sake of minimizing collisions
} Nonce;
~~~

@wangshan, would this work? @ekr, @tgeoghegan, @cjpatton, thoughts?

**Comment by wangshan** [comment]
@chris-wood I think this should work.

**Comment by chris-wood** [comment]
Great! I'll prep a PR.

**Comment by wangshan** [comment]
I would add the `min_batch_duration` can also be of any length, so aligning Nonce with it will make it coarse-grained for use cases where `min_batch_duration` is large, say in hours, but won't be as effective for very small `min_batch_duration`, but I think that should probably be addressed separately.

**Comment by chris-wood** [comment]
> I'm happy with this change, though 16 bytes will be sufficient since clients are supposed to choose this at random. 

Yep 👍
