### ISSUE TITLE
Allow hpke_config to be queried without task_id

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#289]
In [HPKE Configuration Request](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/main/draft-ietf-ppm-dap.md#hpke-configuration-request-hpke-config), the `[aggregator]/hpke_config` endpoint will be called with a `task_id`, unrecognised `task_id` will result in a 404. 
This requires clients (or any entity wishes to call `[aggregator]/hpke_config`) to know a task id in advance. This is unnecessary for deployments that want to share HPKE config across multiple tasks. Can we consider make `task_id` optional in this endpoint, when queried without `task_id`, aggregator returns either one or a list of `hpke_config`.

**Comment by wangshan** [comment]
This relates to issue https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/248

**Comment by cjpatton** [comment]
Works for me!

**Comment by chris-wood** [comment]
Agreed. This is sufficiently orthogonal from #248 and an unnecessary constraint on a deployment.

**Comment by cjpatton** [comment]
One thing to note here is that Aggregator needs to have the option of aborting instead of returning a response, since some deployments will want key separation across tasks.

**Comment by cjpatton** [comment]
I think this is text-ready. @wangshan would you mind writing a PR?

**Comment by tgeoghegan** [comment]
Also relates to #278, in that we can address both of these at once. I sorta buy that #248 is orthogonal, but I don't see why we wouldn't address that problems if we're dealing with this. I think it would save implementations some churn.

**Comment by wangshan** [comment]
@cjpatton yes aiming to have a PR this week
