### ISSUE TITLE
Protocol text should discuss ingestion servers/anonymizing proxies

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#294]
If clients upload reports directly to the leader, then the leader learns things like the client's IP among other identifying metadata. This can be mitigated with the use of some kind of anonymizing proxy, like an [OHAI](https://datatracker.ietf.org/wg/ohai/documents/) server, provided the proxy is not colluding with the aggregator(s).

However, it's not clear that every deployment will be able to use such a proxy, because the aggregators can't run it as a service, and perhaps the cost of deploying this additional actor is prohibitive.

Nonetheless, the protocol should discuss the privacy leaks that result from direct uploads and discuss how deployments might use anonymizing proxies.

**Comment by tgeoghegan** [comment]
#64 discusses a related idea, or a specific way to address this, where uploads would go through the collector.

Also related to this is the notion of a proxy that would batch up reports, which could reduce the operational burden of running an aggregator (i.e., only the proxy needs to be highly available and receive millions of uploads from clients).

**Comment by wangshan** [comment]
batch up can be applied from the client as well, if client is allowed to send a fixed number of reports in a period of time. I feel batching is an implementation detail that helps scaling, not sure if it should be reflected on the protocol level.

But I agree adding description in the protocol about anonymizing, other than batching we can also introduce a jitter in the proxy to break ordering relaitonship.

**Comment by tgeoghegan** [comment]
> batch up can be applied from the client as well, if client is allowed to send a fixed number of reports in a period of time.

This wouldn't help with batching reports across many clients. The idea here is that instead of a leader having to receive a small message from each of a million clients, it could receive one large message from the batching proxy.

> I feel batching is an implementation detail that helps scaling, not sure if it should be reflected on the protocol level.

I wish this was the case, but I think at a minimum the protocol would have to define some kind of "ReportList" structure so that multiple reports could be transmitted in a single message.

**Comment by BranLwyd** [comment]
I suppose different batching strategies could either require protocol support or not:
1) Something like `ReportList` surely requires protocol support.
2) OTOH, an `/upload` endpoint could be implemented as accepting a number of concurrent requests, then writing them all back to durable storage in a single batch/transaction (however that maps back to the durable storage system), before responding to any of the requests.

(1) requires protocol support, but helps even if the performance-limiting factor is e.g. all of the TLS handshakes, message parsing, or some other artifact of receiving many small messages over TLS.

(2) would give many of the advantages of batching without requiring protocol support, and would help most if the underlying performance limits are due to the limits of the durable storage system in use.

**Comment by cjpatton** [comment]
+1 to adding text about the benefits of anonymization, and adding explicit reference to OHTTP (and maybe MASQUE).

**Comment by tgeoghegan** [comment]
I'm going to try to get this done for draft-02, hopefully early next week.

**Comment by cjpatton** [comment]
@tgeoghegan do you wanna try to take care of this for 03?

**Comment by tgeoghegan** [comment]
For DAP-03, we can definitely throw in some text on using OHAI or MASQUE, perhaps in security considerations. I'm inclined to punt on discussing batching of reports and the corresponding API surface since we aren't yet sure that the protocol requires it to function.

**Comment by divergentdave** [comment]
This is addressed in the recent security considerations rewrite, under [section 7.3, Anonymizing proxies](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-anonymizing-proxies).
