### ISSUE TITLE
Code points for VDAFs?

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#295]
Right now the task config consists of:
> A unique identifier for the VDAF instance used for the task, including the
> type of measurement associated with the task.

If memory serves, this text predates the CFRG's adoption of the draft. It might be appropriate this point to pick codepoints for:
* Prio3Aes128Count
* Prio3Aes128Sum
* Prio3Aes128Histogram
* Poplar1

Do folks have an opinion about where these codepoints should live? Following HPKE's lead, we would define them in the VDAF draft. We can prioritize this for VDAF-03, or decide that it's too early to worry about this.

**Comment by tgeoghegan** [comment]
The VDAF draft seems like the right place to define the codepoints. Once `draft-irtf-cfrg-vdaf` becomes an RFC (🤞🏻), we will want new VDAFs beyond Poplar1 and the current Prio3 family to get defined in new CFRG documents. Ideally DAP should be able to use new VDAFs without any changes, errata or addenda to the DAP document(s), so the new CFRG documents should define the VDAF codepoints.

**Comment by chris-wood** [comment]
I agree with @tgeoghegan.

**Comment by cjpatton** [comment]
SGTM. We need codepoints in the VDAF draft for other reasons (see https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/102), so we can use those if/when needed by DAP. if you want to help move this along, please have a look at https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/104.
