### ISSUE TITLE
Consider making batch IDs predictable

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#301]
For fixed-size tasks, the Leader picks a batch ID and passes it to the Collector with the CollectResp. This is so that the batch can be queried later on with a different aggregation parameter (as required for Poplar1). Alternatively, we could arrange for batch IDs to be "predictable" so that the Collector doesn't have to store batch IDs.

_Originally posted by @chris-wood in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/297#issuecomment-1219697601_

**Comment by branlwyd** [comment]
With the current `next-batch` semantics, there is the possibility that a Collector crashing at an inopportune time might lead to a batch being lost permanently.

If batch IDs were predictable, this would be fixable in a fairly straightforward manner (from a [PR comment](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/297#discussion_r948460390)):

> Also, if it's acceptable to allow batch IDs to be enumerable (e.g. a counter, as suggested by others), I think a simpler idempotent design would be to have the Collector track which batch ID is next itself, and change next-batch to something like max-batch to allow Collectors to "start up" without knowing what the next batch is.

**Comment by cjpatton** [comment]
Here would be my suggested change for this: 
* Change type of `BatchID` from `uint8[32]` to `uint64`. Maybe call it `BatchNum`, since "ID" is always a 32-byte string elsewhere.
* Have the Collector specify the `BatchID` in the collect request.
* Allow the Leader to reject `BatchID`s that are too far into the future.

Anything else to consider?

I'll aim to have a PR up by end of week.

**Comment by branlwyd** [comment]
You may wish to change `next-batch` to something like `current-batch` which causes the Leader to return the batch ID that is "current." (Defined as something like "the next batch that will be completed.") This would allow a new Collector to start up with recent data, without needing out-of-band knowledge of the current batch ID.

OTOH, I'm not sure if this `current-batch` functionality is necessary for any currently-planned deployment's needs; it's also possible to say that a Collector should simply start at the first Batch ID & iterate from there to find the latest Batch ID. In that case, the `next-batch` functionality could be dropped.

**Comment by cjpatton** [comment]
Partly solved by #304, we'll continue on in #342, which is more specific.
