### ISSUE TITLE
Align DAP discussion of soundness/correctness/robustness and privacy with VDAF

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#306]
[VDAF's Security Considerations](https://github.com/cfrg/draft-irtf-cfrg-vdaf/blob/main/draft-irtf-cfrg-vdaf.md#security-considerations-security) contains a nice definition and discussion of the notions of privacy (meaning protecting any individual client's measurement from being seen) and robustness (meaning that the aggregates delivered to a collector are accurate aggregations over the inputs).

DAP's security considerations has definitions of privacy and correctness, and we refer to robustness and soundness in a few places. We should align our definitions with VDAF (or just refer to VDAF's definitions) and consistently use the term "robustness" throughout DAP.

**Comment by cjpatton** [comment]
PR, please!

**Comment by tgeoghegan** [comment]
I'm going to get this done for draft-02, hopefully early next week.
