### ISSUE TITLE
Consider adding max_report_size to task parameters

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#311]
Today the report payload size is limited to <1..2^32-1>

```
struct {
  TaskID task_id;
  ReportMetadata metadata;
  HpkeCiphertext encrypted_input_shares<1..2^32-1>;
} Report;
```

In practise, it's very unlikely for client to send report of GB size, large payload also increase performance burden of aggregators. It's likely that the aggregator that need to handle GB or x100MB size of payload to be designed very differently than aggregators only need to handle xMB size payload. We can add a field in task configuration to limit the size that aggregators can accept.

Alternatively we can specify this limit on the aggregators or the whole DAP deployment, but I don't know if there is a way to communicate this capability.

**Comment by tgeoghegan** [comment]
I think the maximum input size of a report will be a function of the VDAF in use. e.g., a report for `Prio3Aes128Sum` with `bits = 16` will always have the same size. I think the same is true for Poplar1, where you have to choose a bit length for the strings being aggregated.

Any report that has a different size will be rejected during decoding (as @simon-friedberger and I learned during a test this week). If we introduce a size constraint at the DAP level, then I worry that we are introducing an opportunity for error by having a DAP-level `max_report_size` that disagrees with the report size dictated by the VDAF.

**Comment by cjpatton** [comment]
I agree with @tgeoghegan, the expected size of the input shares is determined entirely by the VDAF and its parameters. This in turn is determined by the task config, so it should be sufficient to "opt in" to that task.

The same is true for Poplar1. In particular, each measurement is a bit string of some fixed length. For what it's worth, the public share + input shares is about 16.3 KB for 256-bit inputs.

**Comment by cjpatton** [comment]
@wangshan is there anything else you'd like to discuss for this issue or can we close it out?
