### ISSUE TITLE
No public_share in a Report?

### ISSUE THREAD

**Issue by seanturner** [ietf-wg-ppm/draft-ietf-ppm-dap#329]
The presentation syntax is:

    opaque public_share<0..2^32-1>;

Are there ever going to be no public shares in a Report?

**Comment by cjpatton** [comment]
Yes, this is needed for Poplar1. From the [VDAF change log](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-03.html#name-change-log):

> Extend (V)DAF syntax to include a "public share" output by the Client and distributed to all of the Aggregators. This is to accommodate "extractable" IDPFs as required for Poplar1. (See [[BBCGGI21](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-03.html#BBCGGI21)], Section 4.3 for details.)

**Comment by cjpatton** [comment]
@seanturner if you want, we can add text that makes sure your question is answered. Otherwise I don't think there's any action to take here.

**Comment by simon-friedberger** [comment]
> Are there ever going to be no public shares in a Report?

I think the answer should be: "Yes, Prio3 doesn't need public shares."

**Comment by seanturner** [comment]
Thanks for the update.
