### ISSUE TITLE
Review s4.1

### ISSUE THREAD

**Issue by seanturner** [ietf-wg-ppm/draft-ietf-ppm-dap#332]
I was going to rework s4.1 because it repeats the statement about the parameters being defined in subsections below, but I wasn't sure that I would get the flow right.

**Comment by cjpatton** [comment]
I agree this could be improved. I'd be happy to review a PR, but let's perhaps wait for DAP-02 to be cut first?

**Comment by cjpatton** [comment]
#504 removes the first.
