### ISSUE TITLE
Determining query type before parsing a request

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#340]
The query type is determined by the task config, which in turn is determined by the task ID. The task ID is encoded by the message, so it is necessary to parse the task ID before the Aggregator knows how to parse it.

PR https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/297 introduced the following problem: If an Aggregator implements multiple query types ("time-interval" and "fixed-size", say), then a message's format depends on the query type for the task. This means it is necessary to parse the task ID before the rest of the message.

This is perfectly implementable, but it has two downsides:
1. This likely breaks abstraction boundaries in current implementations and will require refactoring. (For example, [here is how reports are handled in Daphne](https://github.com/cloudflare/daphne/blob/main/daphne/src/roles.rs#L251-L255). Notice that the message is parsed in one step.)
2. Going forward, we'll need to make sure that the task ID always appears first in any DAP message so that it can be easily parsed. This is already true today, but we might want to add some text to Operational Considerations that spells this requirement out so that we minimize the chance of regression.

Here's my question for folks: Do we want to try and do something about this? I can think of a couple of solutions:
1. Add the query type byte to messages whose format depends on this. One downside is that it creates a new error case for the Aggregator to check, namely, that the query type indicated in the message matches the query type of the task. (In fact, we tried to avoid this in #297.)
2. Move the task ID out of the message payload and into the URL query string, or perhaps the HTTP header. The only downside to this is that it complicates request authentication for deployments that want to sign the payload and bind it to the task config.  (This may be desirable from a security perspective.) One possible upshot is that it might put us in a better position to address #278. (@tgeoghegan please weigh in here!)

**Comment by cjpatton** [comment]
I noticed this issue while working on the implementation of "fixed-size". I think my preference would be to do nothing here,j i.e., shift the burden to implementations and maybe make a note in Operational Considerations.

**Comment by branlwyd** [comment]
I thought about this too, but I was waiting to finish Janus' DAP-02 implementation to see how impactful it was. (implementation is still ongoing, I'll update this bug w/ my thoughts once we're closer to done)

If we do decide to do something, I think I'd prefer solution #2. We've had a few issues now of the form "correctly parsing this message requires knowing the task ID, which requires parsing part of the message." This is technically feasible (as you note), but is fairly awkward from an implementation standpoint (IMO). Moving the task ID out from the message sidesteps this problem, and IMO fits well with #278.

I think solution #1 would allow implementations to have simpler parsing logic, but I'm not sure this upside is worth the cost of an additional byte on the wire & an additional error case. Though I suppose this new error case exists either way -- but without a discriminator byte, the error case would most likely present itself as a message parsing failure. (e.g. "message has too many/too few bytes")

**Comment by cjpatton** [comment]
After conferring with @wangshan, @MichaelScaria et al offline, we discovered another consideration here which makes me lean towards making protocol messages self-describing (solution (1.)).

We're working on an [extension that would change the semantics of the task ID](https://github.com/wangshan/draft-wang-ppm-dap-taskprov). At a high-level, an Aggregator that supports this extension uses information provided by the client (in a Report extension) to derive the task ID. This information includes, among other things, the query type to use for the task.

The problem is that decoding of the `AggregateInitializeReq` depends on the query type, which, when this extension is in-use, is not known until parsing the report extensions:

```
  struct {
    TaskID task_id;
    AggregationJobID job_id;
    opaque agg_param<0..2^16-1>;
    select (query_type) { /* BUG: This is not known until report_shares is parsed. */
      case time-interval: Empty;
      case fixed-size: BatchId batch_id;
    };
    ReportShare report_shares<1..2^32-1>;
  } AggregateInitializeReq;
  ~~~
```

If we take solution (1.), then `query_type` is encoded by `AggreagtInitializeReq`, thus resolving this bug. There are other ways to resolve this. I can think of a few possibilities if there were an extension field in `AggregateInitializeReq`. However there are lots of things to consider for this sort of change, and I would prefer we wait until later.

Does anyone object to taking solution (1.)? I will have a PR ready for this by the end of the week. I would like to land this in DAP-02 if at all possible.

**Comment by cjpatton** [comment]
PR is up, would appreciate review.

**Comment by tgeoghegan** [comment]
I think that the right solution in the long run is Chris' #2, namely putting the task ID, and anything else needed to parse the request body, into the HTTP request path. But I'm OK with taking #341 for now in the interest of making `draft-02` implementable. Sure, we'll have to take the query type byte out of these messages later, but there are quite a few messages that currently have a `TaskID` or `AggregationJobID` member that will get moved up into the request path in draft-03 (🤞🏻)

**Comment by cjpatton** [comment]
Option (2.) doesn't quite solve my extension problem (https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/340#issuecomment-1247211935), but I have no objection to moving the task ID (and maybe agg job ID) out of the message in any case. Seems to me that this would solve other problems.
