### ISSUE TITLE
Rationale for 2-byte QueryType instead of 1?

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#350]
QueryType is 2 bytes:
```
enum {
   reserved(0), /* Reserved for testing purposes */
   time_interval(1),
   fixed_size(2),
   (65535)
} QueryType;
```

Did we ever discuss a particular rationale for this? I can't imagine needing as many as 65,535 distinct query types; 1-byte (255 distinct types) is definitely sufficient.

**Comment by chris-wood** [comment]
This is definitely a bike shed, but an extra byte here doesn't seems worth trimming. I would leave this as-is. 🤷

**Comment by cjpatton** [comment]
I agree it's a bike shed. If someone wants to send a PR, feel free. Otherwise let's park this.
