### ISSUE TITLE
Specify unrecognized task ID error explicitly in all APIs

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#361]
The current protocol text doesn't specify what participants should do when a task ID is not recognized, there are two places unrecognized task are mentioned:

1. In the [Errors](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/main/draft-ietf-ppm-dap.md#errors) table, it has: 

> unrecognizedTask | An endpoint received a message with an unknown task ID.

2. [`hpke_config` request](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/main/draft-ietf-ppm-dap.md#hpke-configuration-request-hpke-config) mentions "404 Not Found and an error of type unrecognizedTask", which seems to conflict with most implementation's choice of error code 400 (@cjpatton )

The text should specify error 400 with type `unrecognizedTask` is used in every API that receives unrecognized task ID.

**Comment by cjpatton** [comment]
This would be useful I think. Would you mind sending a PR, @wangshan?

**Comment by wangshan** [comment]
@cjpatton will do, create this issue to remind myself.

**Comment by wangshan** [comment]
PR #363 merged
