### ISSUE TITLE
`struct BatchSelector` is redundant

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#366]
In DAP-02, we define [`struct Query`](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.1):
```
enum {
  reserved(0), /* Reserved for testing purposes */
  time_interval(1),
  fixed_size(2),
  (255)
} QueryType;

opaque BatchID[32];

struct {
  QueryType query_type;
  select (Query.query_type) {
    case time_interval: Interval batch_interval;
    case fixed_size: BatchID batch_id;
  }
} Query;
```

Which is then used in [`CollectReq`](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.1):
```
struct {
  TaskID task_id;
  Query query;
  opaque agg_param<0..2^16-1>; /* VDAF aggregation parameter */
} CollectReq;
```

But later, we define [`AggregateShareReq`](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.2) in terms of `struct BatchSelector`:

```
struct {
  QueryType query_type;
  select (BatchSelector.query_type) {
    case time_interval: Interval batch_interval;
    case fixed_size: BatchID batch_id;
  };
} BatchSelector;

struct {
  TaskID task_id;
  BatchSelector batch_selector;
  opaque agg_param<0..2^16-1>;
  uint64 report_count;
  opaque checksum[32];
} AggregateShareReq;
```

Is there a reason we don't use `Query` in `AggregateShareReq`? `AggregateShareReq` and `CollectReq` should be very similar.

**Comment by cjpatton** [comment]
Yes, Query and BatchSelector are the same struct. I wanted to different names because, depending on how we resolve #342, we may want to add additional fields to Query (e.g., "current-batch").

**Comment by tgeoghegan** [comment]
That makes sense. It sounds like the resolution of #342 will either unify these two structs or introduce new fields that make them truly distinct, so I don't think we need another issue about this. I'll add a note in #342 and close this.
