### ISSUE TITLE
SealBase is not defined

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#368]
I only tried searching for it, but all I found were places that it was used.  This makes it difficult to determine which inputs are which.  Which is the AAD, which is the plaintext, and which is the nonce?  Please also *describe* the inputs in text.

Note that at least one of the code blocks that use this is too wide at 76 characters.

**Comment by cjpatton** [comment]
SealBase() and SealOpen() refer to the "single-shot APIs" from https://www.rfc-editor.org/rfc/rfc9180.html#name-single-shot-apis. I notice that we don't reference this explicitly. Would a reference suffice?
