### ISSUE TITLE
Clarify encoding of AAD

### ISSUE THREAD

**Issue by divergentdave** [ietf-wg-ppm/draft-ietf-ppm-dap#371]
Currently, the AAD for input shares is defined as `task_id || metadata || public_share`. The variable `public_share` is narratively introduced in 4.4.1.3 as "the public share sent to each aggregator", referring to a part of the report share. Two implementations interpreted the construction of the AAD differently, as either [including](https://github.com/cloudflare/daphne/blob/61ab97f0c07f9f4bbdb13ec666cebd22febf12ec/daphne/src/vdaf/mod.rs#L184) or [not including](https://github.com/divviup/janus/blob/42873cddb666dce39d27a2342adc3d7232b14eda/core/src/hpke.rs#L37-L49) a 32-bit length suffix preceding the public share.

While it would likely be okay to have a single variable-length byte array in the AAD without a length prefix, as the resulting AAD would still be unambiguous, I think it would be prudent to change this to explicitly include a length prefix, to simplify future changes.

We should define new structs for both kinds of AAD strings, and specify that the AAD is the result of encoding the corresponding struct. For example:

```
struct {
  TaskID task_id;
  ReportMetadata metadata;
  opaque public_share<0..2^32-1>;
} ReportShareAAD;
```

**Comment by branlwyd** [comment]
Places in DAP-02 `public_share` is used without a length prefix:
* Section 4.3.2, in the AAD to `SealBase`.
* Section 4.4.1.3, in the AAD to `OpenBase`.

I think all of the places where we might unexpectedly not have a length prefix will live in the info or AAD parameters to `OpenBase` or `SealBase`, since I think all other encoding is specified via RFC8446 struct notation.

I like the idea of specifying info/AAD values as encodings of an RFC8446 struct, as suggested in the OP: this would be unambiguous, and would lower the odds of regressions if we introduced additional variable-length fields.

**Comment by cjpatton** [comment]
In  interpreted these sections as including the length prefix. The only section where we definitely can't pass the length prefix is https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.4.1.5, where the VDAF is invoked.

**Comment by wangshan** [comment]
> We should define new structs for both kinds of AAD strings, and specify that the AAD is the result of encoding the corresponding struct

I also support this approach in OP, I think all AAD string should be defined in structs and make it explicit that OpenBase and SealBase takes the encoding of such struct for AAD, that means AAD used in Aggregate share encrypt/decrypt in https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.4 should also have a struct definition.

**Comment by wangshan** [comment]
Regarding the VDAF call, am I right TLS is not specified for the procedure calls with VDAF? so public_share can be any type/encoding that VDAF implementation understands, therefore how length of public_share is passed in the below call doesn't have to be constrained by how AAD is used.
```
prep_state = VDAF.prep_init(vdaf_verify_key,
                            agg_id,
                            agg_param,
                            report_id,
                            public_share,
                            input_share)
```

**Comment by cjpatton** [comment]
As input to VDAF, `public_share` is the opaque byte string carried by the `Report`, _excluding_ the prefix. Just as `input_share`, it is decoded as specified by the VDAF in use.
