### ISSUE TITLE
Pre-Aggregation into buckets

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#385]
We are indicating that batches can already start aggregating before the collector sends a query at least in three places:

2.1
> The leader distributes the shares to the helpers and orchestrates the process of verifying them (see [Section 2.2](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#validating-inputs)) and assembling them into a final measurement for the collector. Depending on the VDAF, it may be possible to incrementally process each report as it comes in, or may be necessary to wait until the entire batch of reports is received.

4.4
> Once a set of clients have uploaded their reports to the leader, the leader can send them to the helpers to be verified and aggregated. In order to enable the system to handle very large batches of reports, this process can be performed incrementally.

4.5.2
> Note that for most VDAFs, it is possible to aggregate output shares as they arrive rather than wait until the batch is collected. To do so however, it is necessary to enforce the batch parameters as described in [Section 4.5.6](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#batch-validation) so that the aggregator knows which aggregate share to update.

Optional, but we might want to expand 4.5.2 and give this process a name and clarify what it means to validate a _bucket_ (is this the name we're using?) because some of the point in 4.5.6 don't really apply. For example, a bucket may, by definition, contain too few reports.

**Comment by wangshan** [comment]
Perhaps we should remove the mentioning of 4.5.6, since the "bucket" isn't a final batch and doesn't have to be valid at pre-aggregation stage.

**Comment by cjpatton** [comment]
Blocked on resolving https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pulls?q=is%3Apr+is%3Aopen+label%3A%22aggregation+cost%22, as this will conflict with text changes.

**Comment by cjpatton** [comment]
Just wanted to note an observation here: to specify this normatively, we might need a syntactic change to VDAFs: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/580#discussion_r1765530675

Of course, there is a non-normative way to resolve this PR, which is to define "batch bucket", say there is an aggregate share per bucket, and say that each output share is "added" into the aggregate share of its bucket (without defining "added").

**Comment by branlwyd** [comment]
Closing this issue, as it was addressed in #623.
