### ISSUE TITLE
Clients need to provide nonce when sharding measurements

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#394]
In the upcoming VDAF-04, [`Vdaf.measurement_to_input_shares` now takes a `nonce` argument](https://github.com/cfrg/draft-irtf-cfrg-vdaf/blob/main/draft-irtf-cfrg-vdaf.md#sharding-sec-vdaf-shard). The intention is that clients will use the report ID they generate as the nonce, corresponding to [what we already do when we call `Vdaf.prep_init`](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#section-4.4.1.5). Once VDAF-04 is out, we will need to align DAP's discussion of report construction with it.

**Comment by simon-friedberger** [comment]
I probably missed a discussion elsewhere but why are we adding this?

**Comment by tgeoghegan** [comment]
https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/117 explains why VDAF changed to take a random nonce during input sharding.

**Comment by cjpatton** [comment]
More information here: https://mailarchive.ietf.org/arch/msg/cfrg/-errBjFRvCqi7KuAxoZwH6iY4Vc/

**Comment by simon-friedberger** [comment]
It seems this didn't make it into vdaf-4. Should we also push it to dap-5 then?

**Comment by tgeoghegan** [comment]
VDAF-04 has the [necessary definition of `Vdaf.measurement_to_input_shares(measurement: Measurement, nonce: Bytes[Vdaf.NONCE_SIZE]) -> (Bytes, Vec[Bytes])`](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf-04#name-sharding-2) so we're good here.

**Comment by simon-friedberger** [comment]
Ah, okay, I searched from the beginning and it's missing in 4.1.

**Comment by cjpatton** [comment]
Yeah so far we don't see a need for providing a nonce for DAF sharding.
