### ISSUE TITLE
Aggregate results should include the interval of time that the constituent reports span

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#397]
[In DAP-03](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#section-4.5.2-13), the results of an aggregation are presented to the collector as:

```
struct {
  PartialBatchSelector part_batch_selector;
  uint64 report_count;
  HpkeCiphertext encrypted_agg_shares<1..2^32-1>;
} CollectResp;
```

where `encrypted_agg_shares` is the encrypted form of [a VDAF's `AggResult` associated type](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf-03#name-constants-and-types-defined). In the case of a time interval task, the collector will have explicitly requested collection over some interval of time, but in the case of a fixed size task, that aggregate result will have been compiled from a set of reports chosen by the leader. So the collector can only infer that the reports are from no later than when the collect request came in and no sooner than when the collector got the previous batch.

DAP should explicitly tell the collector what time interval is covered by a collected batch.

**Comment by tgeoghegan** [comment]
One way to do this would be to amend `PartialBatchSelector`. [In DAP-03](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#section-4.4.1.1-4), it is defined as:

```
struct {
  QueryType query_type;
  select (PartialBatchSelector.query_type) {
    case time_interval: Empty;
    case fixed_size: BatchID batch_id;
  };
} PartialBatchSelector;
```

We could add an `Interval` to the `fixed_size` case. However that is awkward because `PartialBatchSelector` is also used in `AggregateInitializeReq`, so we have to make sure that there's something cogent the leader could put there.

Another, simpler choice is to simply add an `Interval` field to `CollectResp`, but the downside there is that this information isn't useful in the time interval case, because the collector already knows what time interval it queried over.

**Comment by cjpatton** [comment]
I'm cool with adding an `Interval` with the minimum and maximum timestamp of all reports in the batch. I think overloading `PartialBatchSelector` is not the right approach, however, since this is meant to "partially determine" a batch of reports, where as the interval in our case is strictly informational.

Unrelated follow question: if we define `CollectResp.interval` to be "the minimum and maximum timestamp of reports in the batch" then it's possible that `CollectReq.interval != CollectResp.Interval`. I think this is OK, and might even be useful.

**Comment by branlwyd** [comment]
+1 to not including an `Interval` in `PartialBatchSelector`; instead, I think it should be placed directly in `CollectResp`.

**Comment by tgeoghegan** [comment]
Chris' point that the interval in `CollectResp` could be tighter than what was in `CollectReq` is compelling. I also now think we should put the `Interval` in `CollectResp` (or, well, [it's `Collection` now](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/77cb75a6480a1777cf5ef7c1c6d1d9d12f3c08b2/draft-ietf-ppm-dap.md?plain=1#L1617)). I'll draft this change this week.
