### ISSUE TITLE
Do we need mitigations against the Leader rewinding aggregation job state?

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#401]
#400 introduces a mechanism allowing the aggregators to recover from the loss of an aggregation job message. The idea is that the helper should be ready for the leader to send the same state transition twice.

However, now we have to contend with the possibility of the leader sending two different sets of prepare messages for the same round of a VDAF, which might let the leader learn something about the input shares.

Further security analysis is needed to determine if there are real attacks here. If there are, one possible mitigation is for the helper to keep track of the messages received from the leader, and abort if it detects the leader trying to re-run an aggregation job round with new parameters.

See [previous discussion on this topic](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/400/files#r1082976904).

**Comment by cjpatton** [comment]
Another point of concern here is if the Leader can rerun the Helper with a previous aggregation parameter.

**Comment by cjpatton** [comment]
I think the requirement for any retry mechanism would be that, if the body of the request does not change, then the server treats handles it as a retry; but if the body changes, the server should treat it as an attack. I believe that's exactly what we have, so I'm going to close this with no action.
