### ISSUE TITLE
VDAF security analysis: Requirements for the verification key

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#407]
The analysis posted [on the CFRG mailing list](https://mailarchive.ietf.org/arch/msg/cfrg/-errBjFRvCqi7KuAxoZwH6iY4Vc/) describes the security consideration for DAP:

> Some care is required in choosing the VDAF verification key. The
> Aggregators may use any strategy they wish to exchange this key, but the
> application MUST ensure that the key that is picked independently of the
> reports. For DAP in particular, this means it is safe for the Leader to
> pick the key and distribute it, but the Aggregators need to "commit" to the
> verification key used for a given task and use the same key for the
> duration of the task. (Rotation requires rolling the task configuration.)

Assuming we agree this is an issue that needs to be addressed, what should we do about it?

**Comment by cjpatton** [comment]
One suggestion, due to @hannahdaviscrypto, is to derive the task ID from the verification key by applying a one-way function. That way there is no possibility of the task ID being picked before the key.

Being a bit more careful, we might use HKDF to derive both strings from a shared secret. Perhaps something like:
```
    prk = HKDF-Extract(salt, shared_secret)
    task_id = HKDF-Expand(prk, "task Id")
    vdaf_verify_key = HKDF-Expand(prk, "vdaf verify key")
```

**Comment by simon-friedberger** [comment]
```
When modeling the
function used to derive the challenge as a random oracle, it is sufficient
to ensure that (i) the VDAF verification is fixed prior to the report being
generated _and_ (ii) the nonce is chosen at random by the Client.
```
Should this be an `or`? I think we agreed that using a ROish derivation function including the client nonce would be sufficient, right?

**Comment by cjpatton** [comment]
Actually I intended "and" :)

This security consideration has to do with privacy. For Prio3, we need the "query randomness" generated by the Aggregators to be "fresh". (By "fresh" I mean it needs to be random and the adversary should not be able to influence this value.) Our security model for privacy allows the adversary to pick the verify_key: In order to ensure freshness of the query randomness used for a given report, it is sufficient to (i) pick verify_key prior to generating the report and (ii) choose a random nonce. If we didn't have (i), then attacker controls the query randomness by picking a favorable verify_key to prepare the report with: if we didn't have (ii), then query randomness is predictable to the attacker.

**Comment by simon-friedberger** [comment]
But if the query randomness depends on the report nonce (as in `query_rand = SHA-3(nonce + verif_key + stuff)`) an attacker who controls verif_key can **not** pick a favorable verif_key because of the RO properties.
Right?

**Comment by cjpatton** [comment]
Good question.

So the attacker knows `nonce` and `stuff`, and it can pick `verify_key` before the honest aggregator computes `query_rand`.

Thus, it can query the RO `SHA-3` with different `verify_key`s until it finds one for which the `query_rand` is "favorable". Does this make sense?

In other words, "query_rand" is not uniformly distributed, even though it was output by the RO! Its distribution is biased towards whatever property is favorable to the attacker. For instance, if for some reason `query_rand` is favorable if its first bit is `1`, then the attacker can easily arrange things so that the honest Aggregator computes `query_rand` that begins with `1`.

**Comment by simon-friedberger** [comment]
If this is a problem, the problem also exists with 50% probability when using true randomness, so this shouldn't be an issue.

**Comment by cjpatton** [comment]
>  ... the problem also exists with 50% probability when using true randomness ....

I'm just trying to give an example of how the attacker can bias the randomness. With more random oracle queries, it can fix the first 2 bits, 3 bits, ..., N bits, etc. It doesn't really matter. The point is: This possibility of this attack prevents a reduction to honest-verifier ZK of the FLP. (This is a standard assumption and is what is proven for the FLP we use in Prio3: See [2019/188](https://eprint.iacr.org/2019/188).)

To avoid this, we need all inputs to the random oracle, including `verify_key`, before honest Aggregators compute `query_rand`.
