### ISSUE TITLE
VDAF security analysis: Requirements for report processing

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#408]
The VDAF analysis [posted on the CFRG list](https://mailarchive.ietf.org/arch/msg/cfrg/-errBjFRvCqi7KuAxoZwH6iY4Vc/) suggests the following restrictions is needed:

> Poplar1: Applications MUST ensure that reports are aggregated at most once
> per-level. Repeated usage of the authenticator at a given level may lead to
> subtle attacks on privacy. In particular, the current
> "max_batch_query_count" mechanism of DAP [2, Section 4.5.6] is not
> sufficient.

By "level" we mean the level of the IDPF tree. The basic idea is that the client generates some randomness for each level of the tree, and it is not safe to use this randomness more than once.

Relatedly: 

> Prio3: Applications SHOULD ensure that each report is processed at most
> once. It's probably safe to allow re-processing, but (1) this is not
> captured in our model; (2) this gets hairy in terms of differential privacy
> (see issue https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/94); and (3)
> there doesn't seem to be a good reason to allow this. (It is explicitly
> disallowed in DAP.)

In other words, the safest bet for Prio3 is to make sure we don't use a proof more than once.

In general, VDAFs may need to restrict how a report is processed based on the aggregation parameters with which it was processed in the past.

**Comment by cjpatton** [comment]
@branlwyd suggested that the right place to enforce this is during report processing. We store nonces of previously processed reports; we could also store whatever information we need to restrict future aggregation parameters.

I think the tricky part is how to spell this. I can think of a couple possible directions:
1. Spell out requirements for Prio3 and Poplar1
2. Try to describe things in terms of a generic VDAF (would require some plumbing in the VDAF document)

The first option is easier, but we'd have to update this text whenever we want a new VDAF.

**Comment by tgeoghegan** [comment]
I think we have to do (2), or DAP is falling short of its design goal to be generic over VDAFs.

**Comment by cjpatton** [comment]
Agreed. A third option is to take (1.) for the next draft, but plan on (2.) for a future draft. This would make our job a bit easier for the next VDAF draft!
