### ISSUE TITLE
metadata -> report_metadata renaming inconsistency

### ISSUE THREAD

**Issue by bhalleycf** [ietf-wg-ppm/draft-ietf-ppm-dap#426]
The current version of the draft renames field "metadata" to "report_metadata" in the Report structure, but does not do the same renaming in the ReportShare and InputShareAad structures.  I think this naming should be consistent, though I don't have a preference between the alternatives.

**Comment by cjpatton** [comment]
Thanks for pointing this out! Can you send prepare a PR?

**Comment by tgeoghegan** [comment]
Fixed in #427
