### ISSUE TITLE
Change PRG

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#432]
If we reconsider our choice of PRG we should take into account that:
1. The RNG is modeled as a random oracle in the proofs but this does not necessarily mean that we need a XOF. It might be more efficient to create a seed using something like SHA-3 (or -2) and then applying a fast AES based stream derivation.
2. cSHAKE (which we are currently using) was only defined in NIST SP 800-185 not the original SHA-3 standard (FIPS 202) so it might not be available in some implementations. FIPS 202 has SHAKE which is also a XOF and we are already defining how to encode the binding string. We could simply define something similar to cSHAKE based on SHAKE. (Exact match is not possible due to non-matching constants.)

**Comment by cjpatton** [comment]
Thanks for summarizing this Simon!

This is more of a question for VDAF than for DAP, so I'd like to suggest we move it there.

**Comment by simon-friedberger** [comment]
@cjpatton Maybe you or @divergentdave can do that? You should have write permissions to both repos, right?

**Comment by cjpatton** [comment]
Sure, I just thought you should raise it if you intend to push for this change. In any case it's a question about the underlying crypto, so I'll close this.
