### ISSUE TITLE
Consider adding content type to POST <collection job> request

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#435]
In Daphne we use the media type to help guide request pre-processing, including parsing of resource IDs:
https://github.com/cloudflare/daphne/blob/main/daphne_worker/src/config.rs#L885

The content type is missing from the POST <collection job> request, so we have to handle parsing the collection ID as a special case:
https://github.com/cloudflare/daphne/blob/main/daphne_worker/src/lib.rs#L368-L382

Additional signaling would be help us reduce a little code complexity here.

**Comment by tgeoghegan** [comment]
There is no body to a `POST` request on a collection job (used to poll the job's status), so I don't think it makes sense to include a content type. Do you mean the `PUT` request, used to create the job, whose body is `struct CollectionReq`?

**Comment by cjpatton** [comment]
@tgeoghegan convinced me offline that there is no sense in setting a content-type header for an empty body. We'll figure out some other way to deal with this.
