### ISSUE TITLE
Do we still need `max_batch_query_count`?

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#436]
This seems redundant now that w'ere now enforcing this restriction at the VDAF level:

> Check if the report may still be aggregated with the current aggregation parameter. This can be done by looking up all aggregation parameters previously used for this report and calling
>
> `VDAF.is_valid(current_agg_param, previous_agg_params)`
>
> If this returns false, the input share MUST be marked as invalid with the error report_replayed.

**Comment by divergentdave** [comment]
We'll need to fix #259 as well before eliminating `max_batch_query_count`. (this just came up in another discussion) Otherwise, `max_batch_query_count = 1` is load-bearing in terms of preventing replaying batches with a different set of reports.

**Comment by cjpatton** [comment]
At IETF 118 I volunteered to implement multi-collection and resolve all related open issues.
