### ISSUE TITLE
Error URIs for "bad request" and "internal server error"

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#437]
The spec says problem details with a "type" other than those defined in the draft MAY be used, but MUST NOT overload the URN:

> This list is not exhaustive. The server MAY return errors set to a URI other than those defined above. Servers MUST NOT use the DAP URN namespace for errors not listed in the appropriate IANA registry (see [Section 8.4](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-04.html#urn-space)).

What's the motivation for this "MUST NOT"? Is it strictly necessary?

I ask because there are a number of abort cases not covered by the existing URIs, and I'm not sure how to set the "title". There are two "catch all" aborts in Daphne right now:
1. "badRequest": An error occurred that was triggered by the request.
2. "internalError": The server encountered an unexpected error that it cannot recover from.

I think any implementation of DAP is going to have to cover these cases.

I have two questions:
1. Should we codify these as URIs in the spec, i.e., define "urn:ietf:params:ppm:dap:error:badRequest"?
2. If the answer to (1.) is "no", what are reasonable values for the types? "badRequest" without the prefix?

**Comment by tgeoghegan** [comment]
Bad request is just an HTTP 400, and internal error is just an HTTP 500. These are already well defined by HTTP. I don't think DAP would help anyone by redefining concepts from HTTP. [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807#section-3.1) says that the `type` field is optional ("When this member is not present, its value is assumed to be "about:blank".'), and DAP does not _require_ a problem document: "When the server responds with an error status, it SHOULD provide additional information using a problem document" ([1](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-04.html#section-3.2-2)).

So I think it's all right for a DAP aggregator to return HTTP 400 or HTTP 500 with no problem document at all, if no specific DAP error type applies.

**Comment by cjpatton** [comment]
Ok, that's good enough for me. I'll just remove the type field for these cases.

**Comment by divergentdave** [comment]
The reason for the `MUST NOT` is primarily forward compatibility, as the DAP draft is in charge of this URI namespace, and needs to be able to pick new types in it going forward freely. (Each error type that's defined gets to declare what set of additional attributes are expected, and in each case for DAP's error types, that's just the one for task ID) Catch-all "bad request" and "internal error" errors would be best served by `about:blank` or an absent type, as Tim mentions, but if there's a need for some other kind of custom error type, you could also define your own error type URI, for example with an `https://` URL you control. (The RFC recommends putting some documentation at that URL)
