### ISSUE TITLE
URI template is confusing

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#441]
The `{role}/resource_type/{resource-id}` template doesn't seem to hold.

> A resource's path is resolved relative to a server's endpoint to construct a resource URI. Resource paths are specified as templates like:
>
> ```
> {role}/resource_type/{resource-id}
> ```
>
> `{role}` is one of the API endpoints in the task's aggregator_endpoints (see [Section 4.2](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-04#task-configuration)). The remainder of the path is resolved relative to the endpoint.
>
> DAP resource identifiers are opaque byte strings, so any occurrence of `{resource-id}` in a URL template (e.g., `{task-id}` or `{report-id}`) MUST be expanded to the URL-safe, unpadded Base 64 representation [...]

The literal string "resource_type" does not appear in the document.  Instead, we have things like `{aggregator}/hpke_config` (with no apparent `{resource-id}`) and `{leader}/tasks/{task-id}/reports`.

It seems like you might benefit from the base64url note as a general rule, but the idea that you might define a common template form is probably not right.  Maybe you can limit this text to an explanation that resources are identified using templates relative to a root URL that each aggregator defines.

**Comment by cjpatton** [comment]
Thanks @martinthomson! I agree this change makes sense.
