### ISSUE TITLE
Clients that submit multiple times

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#443]
I don't see a [Client capability](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-7.1.1.2)  that addresses the possibility that a client might make multiple submissions.  Let's say Prio3Sum is in use, a client can't submit a value that exceeds the upload contribution limit, but it could submit multiple times.

See #89 for mitigations.

**Comment by cjpatton** [comment]
Good call, I think it's worth calling this out in the security considerations.

**Comment by chris-wood** [comment]
We [now have text](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-capabilities-and-mitigation) that describes this attack, which landed as part of #488, so we can close this out.
