### ISSUE TITLE
On demand collection

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#444]
It seems like the fixed cadence of collection isn't necessary, but the options are currently limited only by a need to have a demonstrated use case before adding options.

I'm guessing, but the fixed time limit or fixed count might exist in order to cap the amount of state that the leader (or all aggregators) might need to retain to track and prevent replays[^1].  But then the timestamp in uploads should address that, allowing aggregation over arbitrary intervals.  A batching VDAF[^2] might have limits on how many reports can be gathered, just in terms of database size, I guess.

Allowing on-demand collection would allow a collector the ability to trade off between timeliness of information and allowing more reports to accumulate.  Especially in the presence of DP protections (#19), this might allow the collector to control when it pays the DP noise cost of making a query.  For a VDAF that has a cutoff, like Poplar1, deferring a query might allow more information to be made available.

[^1]: The text in the draft isn't very clear about replay attacks: #442.
[^2]: I'm still of the opinion that a unified protocol makes very little sense here.  A Prio implementation carries all the complexity of Poplar in the protocol, which is non-trivial.

**Comment by cjpatton** [comment]
Can you clarify what you mean by "fixed cadence of collection" and "on-demand collection"?

The flexibility of collection is determined by the [query type](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.1) associated with the task:
* For the "time interval" query type, the Collector picks a time interval and gets an aggregate of all reports with time stamps in that time interval (as long as there are a sufficient number of reports)
* For the "fixed size" query type, the Collector gets an aggregate of a batch of reports chosen by the Leader (as long as the size of the batch is within the range specified by the task config)
* Future query types specify their own batch selection criteria and degree of flexibility

**Comment by martinthomson** [comment]
"fixed cadence" = "time interval".  This seems to be very rigid (fixed length intervals).

"fixed size" seems to be bound to have a maximum size.  (The name also implies min=max, which doesn't appear to be the case.)

> Future query types specify their own batch selection criteria and degree of flexibility

"on demand" means that a collector can initiate collection when it wants, not bound by either time or number of reports.  I was thinking that maybe this could happen now as opposed to in the future.

**Comment by martinthomson** [comment]
Based on this, it seems to me like you could just as easily dispense with the idea of query types and instead define query bounds: minimum and maximums for both time and number of records.  Then, if maximums can be unbounded and minimums are zero you have covered a lot of ground.

**Comment by cjpatton** [comment]
Would the idea be that one could mix query "types" arbitrarily? For example, would the following sequence of queries be allowed:
1. Aggregate the last 50 reports you saw.
2. Aggregate all reports between 07:00 and 07:15 hours.
3. (Hypothetical, not currently supported) Aggregate all reports with user agent "Firefox".

This might work, but we need to be careful. One requirement we have to meet is ensure that all batches are non-overlapping (i.e., no two batches contain the same report). This is meant to prevent [intersection attacks](https://docs.google.com/presentation/d/1cJEJ07nF_A0zWU49bQXedtrKLIUBqHrw7xzQZaR8ckg/edit#slide=id.g13d9afd0c43_0_171).

Another consideration is that we would like to avoid storing individual shares. The current restrictions on queries allow us to store these in aggregate instead.

**Comment by chris-wood** [comment]
@martinthomson given that QueryType is extensible, I'd propose that the sort of flexibility you have in mind here be written up and brought to the group as a new draft. I'm going to close this out on that basis.
