### ISSUE TITLE
Clock skew and report inclusion in reports

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#445]
For reports that are submitted to a task with a time interval query, what determines whether a report is included in an interval?  This isn't clear.

Assuming that this is based on the value that clients assign to reports, then clock skew in clients will lead to two edge cases:

1. Submissions for an interval might arrive well ahead of the actual start time.  This is only a problem if the leader (and maybe the helper) don't want to keep that report for the time remaining until the interval starts.
2. Submissions for an interval might arrive well after the end time.

The latter is a problem if the report is delivered around the time that collection commences.  Especially if there are multiple actions in flight.

Let's say that the interval ends and, 10 seconds later, collection is initiated.  At about the same time, the last few reports trickle in.  Which reports make it into the collection are hard to define.  The leader indicates the report count and that might match the report count at the helper - because the leader might concurrently be processing uploads - the set of reports that the leader includes might not match those used by the helper.  The checksum will detect this, but it seems like a trivially avoidable problem.

The leader could ensure that there is a time (based on some agreed allowance for skew) after which it does not accept reports.  After this, it might reject requests to collect until the reports it has received have been delivered to helpers.

**Comment by cjpatton** [comment]
> Assuming that this is based on the value that clients assign to reports, [...]

That's correct.

> [...] then clock skew in clients will lead to two edge cases:
> 
>     1. Submissions for an interval might arrive well ahead of the actual start time.  This is only a problem if the leader (and maybe the helper) don't want to keep that report for the time remaining until the interval starts.

Right. In fact, the Leader is empowered to reject such reports [in the upload flow](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.3.2-22). As is the Helper during the [aggregation flow](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-1.1-5.10).


>     2. Submissions for an interval might arrive well after the end time.
> 
> 
> The latter is a problem if the report is delivered around the time that collection commences. Especially if there are multiple actions in flight.
> 
> Let's say that the interval ends and, 10 seconds later, collection is initiated. At about the same time, the last few reports trickle in. Which reports make it into the collection are hard to define. The leader indicates the report count and that might match the report count at the helper - because the leader might concurrently be processing uploads - the set of reports that the leader includes might not match those used by the helper. The checksum will detect this, but it seems like a trivially avoidable problem.
> 
> The leader could ensure that there is a time (based on some agreed allowance for skew) after which it does not accept reports. After this, it might reject requests to collect until the reports it has received have been delivered to helpers.


Good call out. We are aware of this problem (see [this Janus PR](https://github.com/divviup/janus/pull/1254)), and I believe at some point we had text the effect of "the Leader MUST NOT request an aggregate share for a batch from the Helper until all pending aggregation jobs that pertain to the batch are completed". However I can't find anything about this in the current version.

**Comment by branlwyd** [comment]
> the Leader MUST NOT request an aggregate share for a batch from the Helper until all pending aggregation jobs that pertain to the batch are completed

FWIW, these are the semantics we're working towards implementing in Janus ([relevant issue](https://github.com/divviup/janus/issues/1283#issuecomment-1528089866)). I would be supportive of adding text to this effect to Janus, as AFAICT, a concurrent aggregation completion request & aggregate share request can inherently lead to the Leader & Helper falling out of sync in terms of which reports are included in a batch.
