### ISSUE TITLE
Unique HpkeConfigId

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#448]
>    Aggregators SHOULD allocate distinct id values for each HpkeConfig in
   a HpkeConfigList.  The RECOMMENDED strategy for generating these
   values is via rejection sampling, i.e., to randomly select an id
   value repeatedly until it does not match any known HpkeConfig.

1. Why is this a SHOULD and not a MUST? What happens if you have duplicates?
2. Why does this document take a position on how to generate it? Is there something wrong with just a counter?

**Comment by cjpatton** [comment]
1. If there are duplicates then [the Aggregator is meant to use trial decryption to determine which HPKE config was used by the Client](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.3.2-18). Personally, I don't see a reason we should allow this. I think lifting the SHOULD to a MUST is a good idea.
2. I don't think it needs to, a counter sound just fine.

Stepping back, this language seems like it was lifted from the ECH spec, which has very different requirements for HPKE than we have here.

**Comment by ekr** [comment]
Let's make it a MUST.
