### ISSUE TITLE
Specify the types for each PDU

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#449]
This document contains media type registrations in S 8.1 but afaict the PDUs don't themselves say what type they are.

**Comment by cjpatton** [comment]
What does PDU stand for?

**Comment by ekr** [comment]
protocol data unit (message).

It seems like some of the narrative text says what media type it is but others do not.

**Comment by cjpatton** [comment]
Got it, yes this would be helpful!
