### ISSUE TITLE
What's the difference between a prep message and a prep share

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#451]
~~~
        | AggregationJobInitReq                               |
      I | agg_param, helper_report_share, leader_prep_share_1 |
     N1 |---------------------------------------------------->| I
        |                                  AggregationJobResp | N1
        |                   prep_msg_1, [helper_prep_share_2] | P1
        |<----------------------------------------------------| [N2]
~~~

In this diagram the helper sends both `prep_msg_1` and `helper_prep_share_2`, but the latter only in a multiround exchange? Why is this a distinction that needs to be made at the DAP level? It seems much more intuitive to just have the leader and helper each send opaque messages. This is especially confusing because Section 4.2.2.1 does not seem to make use
of the helper's prep message at all, just its prep share.

As a separate note, having the messages numbered so that the helper's prep shares are even but its prep messages are odd is very confusing.

**Comment by cjpatton** [comment]
As illustrated [in the VDAF doc](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-05.html#figure-6):
![image](https://user-images.githubusercontent.com/3453007/235258388-ba8b3b1b-d9eb-4ef1-8ae7-0ca803ff1d3f.png)

* "prep share" is the value emitted by each Aggregator at the start of each round of preparation
* "prep message" is the result of combining the prep shares into the input for the next round

Concretely, in Prio3 the "prep share" is the Aggregator's share of the "verifier": To check a proof, the verifier shares combined into the verifier, which is used to complete the proof check. For Poplar1 there are two rounds of "prep shares", each serving a specific mathematical function.

> In this diagram the helper sends both `prep_msg_1` and `helper_prep_share_2`, but the latter only in a multiround exchange? 

Yup. So `prep_msg_1` would be sent for any VDAF with at least one round of preparation, and `helper_prep_share_2` would be sent for any VDAF that has at least two rounds of preparation.

> Why is this a distinction that needs to be made at the DAP level? It seems much more intuitive to just have the leader and helper each send opaque messages.

That might work. The reason I made the distinction is that it seems helpful for mapping the different fields of the message to points in the multi-party computation. In particular:
* a prep share is an **output** of `VDAF.prep_next()`, but an **input** of `VDAF.prep_shares_to_prep()`
* a prep message is an **input** of `VDAF.prep_next()`, but an **output** of `VDAF.prep_shares_to_prep()`

> This is especially confusing because Section 4.2.2.1 does not seem to make use of the helper's prep message at all, just its prep share.

Sorry, which section? I can't find 4.2.2.1 in the [editor's copy](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.2.2.1).

> As a separate note, having the messages numbered so that the helper's prep shares are even but its prep messages are odd is very confusing.

I understand. It would be good to do something about this. In the current ping-pong proposal (#393), which this new overview text is meant to reflect, we end up handling multiple rounds of VDAF preparation in each aggregation flow request.

**Comment by ekr** [comment]
https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.4.2.1

>   a prep share is an output of VDAF.prep_next(), but an input of VDAF.prep_shares_to_prep()
    a prep message is an input of VDAF.prep_next(), but an output of VDAF.prep_shares_to_prep()

This seems like maybe a place to make an improvement.

In general, the less that we have to know about the internals of the VDAF the better.

**Comment by branlwyd** [comment]
FWIW, I would be supportive of an update to the VDAF interface such that the usage in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/393 is reduced back to "send a single opaque message per report for each request/response". The current approach has a few disadvantages:
* Aggregators must handle multiple opaque VDAF messages per report with each round, which is more complex than necessary.
* The DAP round no longer matches the VDAF round, which is a source of some confusion.

(This assumes that such an update wouldn't make other use-cases of VDAF impossible, but I think the computation is effectively the same in terms of what is computed in which order. The difference would only be in how much is computed per call to a VDAF function.)

**Comment by cjpatton** [comment]
@branlwyd if I understand your proposal correctly, this simplification is only possible for 2-aggregator VDAFs. Even though DAP is moving to 2-aggregator, the core VDAF document is not.

Instead, perhaps you could propose "wrapper" methods for VDAF preparation that would solve this issue?

**Comment by branlwyd** [comment]
Oh, you're right -- this change would only work if VDAF were specified to 2 aggregators.

A sketch of the functions we'd want:

* DAP initialization: no change here; this is a fusion of the sequence of `prep_init`, `prep_next`. The input is the input share (and public share, etc), the output is the initial preparation state & preparation share. Used to implement leader & helper initialization. (I believe `libprio-rs` already implements its initialization functionality in this way.)
* Step: a fusion of a sequence of `prep_next`, `prep_shares_to_prep`, `prep_next`. The input is a prep message and possibly a (next-round) prep share; the output is the equivalent of a #393 PrepareStep's (continued, finished, finish) cases -- possibly a prep message and, if so, possibly a next-round prep share. This is used to implement leader initialization, leader continuation, and helper continuation.
* Helper post-initialization step: a fusion of a sequence of `prep_shares_to_prep`, `prep_next`. The input is a pair of prep shares; the output is a prep message and possibly a prep share. This is used to implement helper initialization.

(note: the wrapper functions working out this way requires moving the `prep_next` currently described in #393 at the beginning of leader continuation to instead be described at the end of both leader initialization & continuation.)

But we should consider carefully if specifying these wrapper functions is actually a complexity win -- the additional layer of indirection might end up making things harder to understand, especially if specified in DAP. VDAF would want to consider the complexity of supporting two different interfaces, if we were to specify the change in VDAF.

**Comment by cjpatton** [comment]
> A sketch of the functions we'd want:

This sounds about right to me. One another note: In general, prep_shares_to_prep() is sensitive to the order of its inputs. In particular the first should be the Leader's and the second should be the Helper's.
 
> But we should consider carefully if specifying these wrapper functions is actually a complexity win -- the additional layer of indirection might end up making things harder to understand, especially if specified in DAP.

Right, but I think it's worth giving it a shot. I'll take a crack at this.


> VDAF would want to consider the complexity of supporting two different interfaces, if we were to specify the change in VDAF.

For the moment we should assume (a) VDAF's interface won't change significantly and (b) VDAF will continue support more than two Aggregators.

**Comment by branlwyd** [comment]
OK. One additional concern is around "the wrapper functions working out this way requires moving the prep_next currently described in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/393 at the beginning of leader continuation to instead be described at the end of both leader initialization & continuation" -- I think phrasing things this way would require marginally more storage. (we'd end up storing a `prep_msg` and `prep_share`, rather than just a `prep_msg`, with each DAP round)

I did things this way because, otherwise, the "fused" functions we end up with are much more complicated.

**Comment by cjpatton** [comment]
PR is ready for review: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/461

I don't think we can avoid the distinction between prep messages and prep shares, but we can at least encapsulate in a way that makes it irrelevant to a higher level understanding of the protocol. FWIW, the distinction *always* mattered, it's just that it was easier to brush under the rug in the previous aggregation flow. "Ping-ponging" a la #393 makes this distinction harder to brush aside.
