### ISSUE TITLE
Why should job IDs be pseudorandom?

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#452]
>   1.  Generate a fresh AggregationJobID.  This ID MUST be unique within
       the context of the corresponding DAP task.  It is RECOMMENDED
       that this be set to a random string output by a cryptographically
       secure pseudorandom number generator.

This seems unhelpful. Either these should be cryptographically random
in which case this should be a MUST, or it doesn't matter, in which case
why is this text here? How am I supposed to know.

**Comment by cjpatton** [comment]
The idea of the RECOMMENDATION here is to suggest a simple strategy for choosing IDs in a way that satisfies the requirement, which is uniqueness. A CSPRNG is certainly not required here.

How about instead of

> It is RECOMMENDED that this be set to a random string output by a cryptographically
secure pseudorandom number generator.

we go with something like

> The ID MAY be chosen at random.

**Comment by ekr** [comment]
I would propose just not saying how it's generated at all.
