### ISSUE TITLE
Handling missing state

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#455]
> 1. Finally, if an Aggregator cannot determine if an input share is valid, it
   MUST mark the input share as invalid with error `report_dropped`. For
   example, if the Aggregator has evicted the state required to perform the
   check from long-term storage. (See {{reducing-storage-requirements}} for
   details.)

Is this aggressive enough? I think we need to be careful that state exhaustion
can't be used to enable differencing attacks where only some inputs are removed.
Need to think more about this.

**Comment by cjpatton** [comment]
What do you mean by "differencing attacks"?

One condition this text envisions is tracking report IDs for replay protection. We don't want to require Aggregators to keep this state forever; they should be allowed to drop report IDs for old reports, say, older than a week. Suppose an Aggregator just that. Then if it receives a report older than a week, it can't determine whether the report is replayed. Instead, it should reject the report to be on the safe side.

**Comment by cjpatton** [comment]
I don't think there's anything to do here.
