### ISSUE TITLE
min_batch_size

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#456]
> The query configuration specifies the minimum batch size, `min_batch_size`, and
maximum batch size, `max_batch_size`. The Aggregator checks that `len(X) >=
min_batch_size` and `len(X) <= max_batch_size`, where `X` is the set of reports
in the batch.

Shouldn't this be *valid* reports in the batch?

**Comment by cjpatton** [comment]
Yeah that's correct. We should be probably be more explicit.

**Comment by tgeoghegan** [comment]
Let's take this for draft-05 as it should be an easy fix.
