### ISSUE TITLE
Overhaul security considerations

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#460]
The security considerations section has lots of out of date content, especially in the threat modeling section that tries to match up actor capabilities with protocol mitigations (see for instance #443). We should review this section of the draft to bring it up to date.

**Comment by tgeoghegan** [comment]
There's also some sections sprinkled throughout the text (like the various "message security" bits) that properly belong in security considerations.

**Comment by simon-friedberger** [comment]
I think it would be good to add a bit more discussion regarding the document by Kyle: https://docs.google.com/document/d/1BdKOLrv0auHUEOo6YbCo6KaqfPC7leuzEfGPngoI_nk to #sybil.

**Comment by simon-friedberger** [comment]
> The Helper then encrypts agg_share under the Collector's HPKE public key as described in [Section 4.6.4](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#aggregate-share-encrypt), yielding encrypted_agg_share. Encryption prevents the Leader from learning the actual result, as it only has its own aggregate share and cannot compute the Helper's.

There is an assumption here that the collector will not share the result with the leader but it violates neither privacy nor robustness. It seems we are missing a requirement about aggregate output confidentiality.
