### ISSUE TITLE
Leader's batch-size check during collection is insufficient.

### ISSUE THREAD

**Issue by branlwyd** [ietf-wg-ppm/draft-ietf-ppm-dap#466]
[DAP-04 Section 4.5.1 Collection Job Initialization](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-04.html#name-collection-job-initializati) says:
> Upon receipt of a CollectionReq, the Leader begins by checking that it recognizes the task ID in the request path. If not, it MUST abort with error unrecognizedTask. Then, the Leader verifies that the request meets the requirements of the batch parameters using the procedure in [Section 4.5.6](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-04.html#batch-validation). If so, it immediately responds with HTTP status 201.

[DAP-04 Section 4.5.6 Batch Validation](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-04.html#name-batch-validation) says:
> Next, the Aggregator checks that batch contains a valid number of reports, as determined by the query type. If the size check fails, then the Aggregator MUST abort with error of type "invalidBatchSize".

The intent of this check is to avoid aggregating batches with too few reports. The correct number of reports to count is the number of successfully-aggregated reports, as this is the number of reports that would be reflected in the eventual aggregate received by the collector. However, it doesn't make sense to evaluate this check here for a few reasons:

* The aggregation process is independent of the collection process, and may not yet be complete -- so at this point, the Leader has no way to know how many reports will eventually be included in the batch. (Indeed, for VDAFs with nontrivial aggregation parameters such as Poplar1, the aggregation process may not _start_ until after the collection request is received.)
* The size of the batch may be lower-bounded by the number of reports that have already successfully completed aggregation, but this does not help to check a fixed-sized task's maximum batch size.

(Even worse, it is arguably DAP-compliant to evaluate the "number of reports" check as "reports received" rather than "reports successfully aggregated". If so, a buggy/malicious Helper might be able to take advantage of this situation to generate aggregates over batches which do not meet the minimum batch size, breaking the desired privacy property. I suspect we should tweak the language of the batch size check to specify successfully-aggregated reports.)

My recommendation is to move the Leader's batch-size check to "just before issuing an `AggregateShareReq` to the Helper", as at this point the Leader can determine the exact number of reports that are aggregated & is therefore in position to accurately evaluate the batch size requirements. I think the Helper's check is fine, though as noted we might want to update wording such that aggregators are evaluating batch size as "successfully aggregated reports" rather than "reports received".

**Comment by branlwyd** [comment]
(for reference/an implementation example, a related issue from Janus: https://github.com/divviup/janus/issues/1414)

**Comment by tgeoghegan** [comment]
I agree with Brandon here. The existing leader check at the time of creating collection jobs should at most be a SHOULD, but can only be a MUST at the time of constructing an aggregate share, and so for simplicity's sake I feel we should remove the batch size check at collection job creation time.
