### ISSUE TITLE
Sync with latest VDAF draft

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#470]
Once the next draft of VDAF is published (likely to be 06), we need to align DAP with the changes it makes. Among other things:

- Update text added in #393 to use correct references to ping-pong wrappers added in https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/240

**Comment by cjpatton** [comment]
VDAF-06 is out: https://datatracker.ietf.org/doc/draft-irtf-cfrg-vdaf/06/

**Comment by wangshan** [comment]
Related: `ping_pong_start` in VDAF-06 has a nonce parameter, but not in this DAP version.

**Comment by tgeoghegan** [comment]
> Related: `ping_pong_start` in VDAF-06 has a nonce parameter, but not in this DAP version.

It does, we use the DAP report ID as the VDAF nonce, which is explained in the text below.
