### ISSUE TITLE
Order of string literals in SealBase

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#478]
I noticed for aggregation share, the string literal 0x00 is concatenated after server_role,
```
enc, payload = SealBase(pk, "dap-04 aggregate share" || server_role || 0x00,
  agg_share_aad, agg_share)
```

For others like PlaintextInputshare it's before server_role:
```
enc, payload = SealBase(pk,  "dap-04 input share" || 0x01 || server_role,
  input_share_aad, plaintext_input_share)
```

Is there a reason behind this difference, or should we just unify them?

**Comment by divergentdave** [comment]
I think these are intended to be fixed roles, so `0x00` represent the collector, and `0x01` represents the client. The position is determined by which participant is the sender and which is the receiver, which explains why the order of the literals differs. We should probably clarify where these come from in the following prose. Alternately, we could replace the string literals with references to the enum's variants, but I'm not sure if there's accepted syntax for enum literals outside the context of a `select`.

**Comment by wangshan** [comment]
I see, I guess this is mainly for debugging? I agree explain it somewhere in the text would be sufficient.
