### ISSUE TITLE
Do we still need `max_batch_query_count`?

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#497]
Discussion in #495 leads us to believe that we might want to remove the DAP-level concept of `max_batch_query_count` and replace it with a VDAF-specific check that would take into account the history of queries made against a batch. We don't yet completely understand what the shape of that check is.

**Comment by cjpatton** [comment]
VDAF requires that we do aggregation parameter validation, i.e., before agreeing to run a collection job with aggregation parameter `agg_param`, it must be that `Vdaf.is_valid(agg_param, prev_agg_params) == True`, where `prev_agg_params` is the set of aggregation parameters used previously for collecting the batch: https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#section-5.3

DAP enforces this here: https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.5.1.4-3.6.1

Note that this is a vestige from at least draft-00 (it used to be called `max_batch_lifetime`). The VDAF-level check is stricter (and necessary according to {{DRPS23}}), so we can probably just get rid of it.

**Comment by cjpatton** [comment]
Oops, this is a dup of https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/497. Sorry about that.
