### ISSUE TITLE
Report selection

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#499]
The Leader sees client IP addresses and can easily inject and drop reports. This puts the Leader in a powerful position for Sybil attacks. On the surface, it seems like an interesting suggestion to let the Helper select the reports for a certain aggregation instead.

Here are some counterarguments:
1.. The helper needs to explicitly mix reports for this to have any effect.
2. The leader can still single out reports by dropping and injecting sufficiently many to make the mixing ineffective.
3. An OHTTP server to obfuscate client identities might be more beneficial anyway.
4. Sybil attack protection would limit what the leader can do to single out reports.

**Comment by cjpatton** [comment]
>  On the surface, it seems like an interesting suggestion to let the Helper select the reports for a certain aggregation instead.

What's the Helper behavior your envisioning here?

Have you had a look at https://github.com/cpriebe/draft-priebe-ppm-dap-reportauth? The idea suggested there is that the Helper (and Leader, in fact) would only accept reports from clients that got issued a valid (rate-limited) PAT.

**Comment by simon-friedberger** [comment]
The leader would submit all reports to the helper and the helper would select which reports go into a specific aggregation. This should make it harder for the leader to pick reports by a specific client and aggregate them with fakes to break privacy.

**Comment by wangshan** [comment]
I think a report authentication scheme like https://github.com/cpriebe/draft-priebe-ppm-dap-reportauth plus IP anonymisation like OHTTP would resolve this issue nicely.

**Comment by chris-wood** [comment]
+1 -- authenticating reports and anonymizing the upload flow seems like it addresses the issue. Closing on that basis.

**Comment by chris-wood** [comment]
Actually, let's just add some text describing these options for deployments that need to worry about this particular threat.
