### ISSUE TITLE
Making privacy-relevant task parameters visible to clients

### ISSUE THREAD

**Issue by divergentdave** [ietf-wg-ppm/draft-ietf-ppm-dap#500]
The `min_batch_size` task parameter is relevant to the question of how well a given DAP tasks protects the privacy of its measurements. While agreement on the value of `min_batch_size` is out of scope of the protocol, both Aggregators must know its value. In some deployment scenarios, we may have the goal that that reverse engineering a Client provides enough information to assess how the privacy of measurements is protected. It would be easy to distribute `min_batch_size` to the Client as well, but it does not make use of this value, and any results would require trust in the means by which this `min_batch_size` was distributed to the client, on top of the Aggregator non-collusion assumption.

We could provide more robust transparency for this parameter in a couple ways: either by asking both aggregators, or by having the Client commit to its view of the parameter and honest Aggregators checking this commitment.

On-line verification verification of parameters would require both Aggregators to support some new endpoint, and return a select set of task parameters in response to requests for a particular task. Someone auditing a Client implementation could identify the task ID and aggregator endpoints, query both aggregators, confirm that they match, and then assume that aggregate shares will obey the `min_batch_size` restriction. It would not be necessary for clients to check this endpoint before uploading.

Having clients commit to `min_batch_size` is already accomplished by the [`taskprov`](https://datatracker.ietf.org/doc/draft-wang-ppm-dap-taskprov/) draft, because `min_batch_size` is hashed into the derivation of the task ID. If we assume that at least one aggregator is honest and that it only accepts task parameters via the `taskprov` header mechanism, then it must agree with the client on the value of `min_batch_size`, and we know it will follow that when releasing aggregate shares. (if there is one dishonest Aggregator claiming to use `taskprov` and one honest Aggregator that accepts any set of task parameters from the dishonest Aggregator via a non-`taskprov` means, then this falls apart)

There are other ways one could achieve the same commitment, without taking on the entirety of `taskprov`. For example, we could distribute `min_batch_size` to the client, and have it include it in some new extension in both report shares. We know this will be distributed to both Aggregators, since extensions are included in the HPKE AAD. Then, both Aggregators would check that the client's view of task parameters matches theirs, and proceed if it does. Alternately, we could consider adding `min_batch_size` to the report share AAD. This would save a few bytes per report, at the expense of requiring that Clients always be provided this parameter.

If we consider cases where the Aggregators add noise to aggregate shares for differential privacy, then we would want to include differential privacy parameters along with `min_batch_size` in the above mechanisms as well. As before, once we have confirmed that the Client and both Aggregators have a common view of the DP parameters, then we assume that at least one honest Aggregator will add noise following those parameters to all aggregate shares. (or, if noise is added inside MPC instead of in the clear by each Aggregator, we would have a stronger conclusion)

**Comment by wangshan** [comment]
> For example, we could distribute min_batch_size to the client, and have it include it in some new extension in both report shares. We know this will be distributed to both Aggregators, since extensions are included in the HPKE AAD

@divergentdave this is the approach used by old taskprov-02, but since the core protocol moved extension to each share, this method is deemed too costly. 

You are right that differential privacy parameters should also be included, taskprov includes a [DpConfig](https://www.ietf.org/archive/id/draft-wang-ppm-dap-taskprov-04.html#section-3-11) that meant to capture DP related parameters. In fact, taskprov wants to make all the task parameters visible to clients, because all of them together form the privacy guarantee DAP promises. For example, [VdafConfig](https://www.ietf.org/archive/id/draft-wang-ppm-dap-taskprov-04.html#section-3-9) is also important because the Differential Privacy parameters will only make sense if the right VDAF is used. 
Perhaps we can propose a "taskprov-lite", which uses taskprov's design to pass task parameters from client to aggregator, allowing aggregators to verify the parameters, without enforcing them to provision the task on-demand.

**Comment by simon-friedberger** [comment]
Since the aggregators are supposed to know the parameters already it would be sufficient to include them as AAD in the authentication of the reports.

**Comment by chris-wood** [comment]
@wangshan I agree with the goal of splitting taskprov into two problems: parameter transparency and task provisioning. Would it be possible to refactor the taskprov draft such that deployments can choose when they want to transparency vs when they want on-demand provisioning support? If so, I think we can close this issue out and use that draft to track resolution.

**Comment by cjpatton** [comment]
The taskprov draft specifies and encoding of the task configuration that is used to derive the task ID. I really like this feature of the extension because it means that successful upload/aggregation/collection implies agreement on the task configuration. I think this would be a cool feature to have in the core DAP protocol.

**Comment by cjpatton** [comment]
> Since the aggregators are supposed to know the parameters already it would be sufficient to include them as AAD in the authentication of the reports.

It should also be sufficient to derive the task ID from the task config, as taskprov does. This is nice because it doesn't require wire changes.

**Comment by simon-friedberger** [comment]
@cjpatton True, but it conflicts with the suggestion that task ID should be based on the verification key to ensure that the aggregators agree on a verification key before reports are generated. (This could probably be handled by distributing a hash of the verification key to clients.)

**Comment by cjpatton** [comment]
Well, could you derive the task ID from both the verification key and the task config and accomplish the same thing?

**Comment by simon-friedberger** [comment]
It should be doable, yes. IIRC clients are not allowed to have the verification key, right? I cannot find this in the current version of the draft.

**Comment by cjpatton** [comment]
That's right: knowning the verification key would allow them to break robustness.

**Comment by npdoty** [comment]
Agreement on parameters being visible to the client (even if it relies on at least one of the parties being honest) would contribute to an important privacy goal, transparency about the privacy parameters of what measurements the client is engaged in.

**Comment by npdoty** [comment]
I understood the conversation to conclude that the goal could be accomplished through multiple means, including taskprov or a different extension to dap. But that currently those extensions do not exist. 

If you want to close this issue, just let me know where I should open the issue to track whether/where the visibility property is satisfied.

**Comment by cjpatton** [comment]
> I understood the conversation to conclude that the goal could be accomplished through multiple means, including taskprov or a different extension to dap. But that currently those extensions do not exist.

Yes, that's right.

> If you want to close this issue, just let me know where I should open the issue to track whether/where the visibility property is satisfied.

We believe this notion of visibility is satisfied by taskprov. It could also be satisfied by a not-yet-defined extension that encodes the privacy-relevant parameters in a report extension. (The Aggregators would check that the parameters sent by the client match the task.)

You're right that we didn't settle whether this property should be a requirement for the core DAP protocol. It's definitely worth settling this before closing the issue. I'm not sure we all agreed this should be a requirement, but we could at least strongly suggest it.

Here is an implementation of [Proposal 3 from "DAP open issues" slides](https://datatracker.ietf.org/meeting/118/materials/slides-118-ppm-dap-open-issues), except the MUST is changed to a SHOULD: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/524

Please take a look!
