### ISSUE TITLE
Align VDAF interface with vdaf-07

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#502]
The latest VDAF has simplified its API with verbs: https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/267.
A few places in DAP is still using the old ones.

**Comment by cjpatton** [comment]
👍 please send a PR when you have the chance.

**Comment by cjpatton** [comment]
Closed by #503.
