### ISSUE TITLE
Widen `PrepareError` to 2 bytes

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#514]
@tgeoghegan @cjpatton the size increase [of `PrepareError` from 1 byte to 2] is to account for random selection of new error types for experimentation. But we can do that separately, if at all, so I'll revert it from this PR.

_Originally posted by @chris-wood in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/509#issuecomment-1771867183_

**Comment by simon-friedberger** [comment]
It seems like it wouldn't be too hard to fix this later and we definitely don't need it at the moment. It also wouldn't be a huge increase in cost. @chris-wood do you want to make a case for this?

**Comment by cjpatton** [comment]
I'll try to remember to bring this up if time permits tomorrow.

**Comment by chris-wood** [comment]
Honestly, I'd be fine closing this.
