### ISSUE TITLE
Versioning PPM media types

### ISSUE THREAD

**Issue by suman-ganta** [ietf-wg-ppm/draft-ietf-ppm-dap#541]
PPM prescribed media types do not have version component in them. As DAP protocol progressing, the structures are changing in a non-compatible way. In order to consistently decode those structures, we need an indicator on what structure to use to decode them with.

I propose adding a MIME parameter, `version`, to express the version of the payload.

Ex: To represent Report structure of protocol version DAP-09, use the media type - `application/dap-report;version=09`

Leader/Helper need to rely on this MIME parameter to consistently parse the payload received, and should also be used to reject unsupported versions.

**Comment by suman-ganta** [comment]
Agreed on path based ways to distinguish versions as an alternative.

But, given that we are defining a dedicated mime type (`application/dap-report`), and not using a generic mime type (`application/octet-stream`), the type should also indicate how to decode it. The encoding is purely based on a specific version and the type information is not part of the stream. So for the reasons of making it self describable as much as possible, I think it is important to express version there.

* It is not a problem for textual structured payloads such as json (`application/json`) since the structure has delimiters.
* It is not an issue with protobuf (`application/protobuf`) since the message encapsulates the field boundaries.

**Comment by cjpatton** [comment]
@suman-ganta please prepare a PR when you have a moment.

**Comment by mnot** [comment]
My .02 - it's fine to add a version parameter (or something else) for draft development purposes. When it ships, however, there shouldn't be any need for a version; the media type _is_ the version identifier.

**Comment by mnot** [comment]
If it's a new major version, it needs a new media type.

**Comment by suman-ganta** [comment]
> If it's a new major version, it needs a new media type.

That makes sense. But the current media types do not have any version embedded in them, So we need one of the following:

Option-1:
Add version to the existing mime types. Which means, change current report mime type from `application/dap-report` to `application/dap-report_01`.
Similar naming will be followed for major/incompatible revisions.

Option-2:
maintain a mandatory MIME parameter (version=) that points to a semver of the entity.

**Comment by cjpatton** [comment]
It seems like a safe  bet that this document will be "DAP v1" and a future document with be "DAP v2". What about something like `application/dap1-report`?

**Comment by mnot** [comment]
Remember that they're opaque strings; the first version could be `application/dap-report` and the second could be `application/dap2-report` or even `application/dap-results`.

**Comment by wangshan** [comment]
I'd prefer we keep the first version as `application/dap-report` and the implementation can optionally add `;version=0x`.
If we have a second version we can have `application/dap2-report`.

**Comment by suman-ganta** [comment]
Why do we need to treat first version differently from the rest?

**Comment by wangshan** [comment]
I don't have a good reason other than existing MIME types seem to follow that, I don't see any common media types have version1 in the name. Besides, we don't know if there will be dap2, or whether it will still be called dap.

**Comment by suman-ganta** [comment]
Right. Which is why I was proposing version as a mime parameter.

I'm not sure if there are other cases where tls encoding is used in http layer, but having no version info doesn't help to decode it in a deterministic way.

**Comment by suman-ganta** [comment]
I would love to see another non DAP tls encoding mime type, if exists, and the practice followed there. 

To me, this is analogous to expressing decoder parameter for video mime types. Without them, there is no consistent way to decode the stream.

**Comment by cjpatton** [comment]
I'm not aware of such a thing. One example we might follow is OHTTP, which uses yet another serialization format: https://www.rfc-editor.org/rfc/rfc9458.html#section-9

**Comment by cjpatton** [comment]
IETF 120: There was opposition to merging #568. @bemasc (as chair) suggested we get some advice from an HTTP expert about whether normative language for media type parameters is needed. I will take this action.
