### ISSUE TITLE
Support for batched preparation

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#561]
There is a [new paper](https://eprint.iacr.org/2024/666) (to appear at IEEE S&P 2024) that shows how to lift an [FLP](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf-09#section-7.1) into a proof system that is "silently verifiable". For such a proof system, it's possible to check if _some_ measurement in a set of measurements is invalid, exchanging only a constant number of bits (128). In Prio3, we must exchange a number of bits linear in the number of measurements.

The bandwidth savings are significant. For Prio3SumVec with bits=1, length=1,000, and chunk_length=32 and 100 reports, an `AggregationJobInitReq` is 122KB. If we modified Prio3 by making the FLP silently verifiable, the same message would be roughly 7KB (back-of-a-napkin calculation). Computational cost remains about the same. (See Figure 7 from the paper for details.)

This approach does a have a potential downside: if verification fails, then we learn only that _some_ measurement is invalid, not _which_ measurement is invalid. Thus, in the case that some fraction of the reports in the aggregation job, you either need to throw away the data or exchange more bits in order to find the subset of measurements that are invalid. The communication cost increases as the fraction of malicious Clients increases.

There are many ways we might implement this. Perhaps the simplest would be to treat batched preparation as an alternative aggregation flow that falls back to the existing aggregation flow (i.e., per report validation) if verification fails. Concretely, we would specify an alternative aggregation sub-protocol that is the same as the existing flow except:
1. It is only compatible with 1-round, "silently verifiable" VDAFs.
2. If verification fails, then it needs to be safe to fallback to per-report validation.

**Comment by wbl** [comment]
Via coding theory you can survive a handful of bad reports and remove them (https://www.nature.com/articles/s41586-020-2885-5 is one reference but there are others)

**Comment by cjpatton** [comment]
That's a super interesting idea! Care to flesh it out a bit more, even if just for fun? 

The problem at hand is to minimize the communication cost (bits on the wire, number of round trips) when you expect X% of the reports to invalid. Though I think there will always be a need to fallback to per-report verification.

**Comment by cjpatton** [comment]
There is a draft PR (#565) with a proposal of how to integrate this into DAP. In the meantime, I've been looking at how much bandwidth savings we would actually get.

Unfortunately, **[Whisper](https://eprint.iacr.org/2024/666) provides no benefit for DAP, even if all clients are honest.** In Whisper, each Client sends some additional information to each Aggregator. The number of bytes included in the report is roughly as much information as is exchanged during per-report preparation Prio3.

In more detail, the Client sends to each Aggregator the verifier share that would be computed by its co-Aggregator. This is denoted by $\mathsf{vtag}_{\mathsf{NS},i}$ in Figure 4 of the paper. (In the transformation from to the "silently verifiable" proof system, the Aggregators arrange to check that Client sent the correct value. This is morally similar to how we check that joint randomness computation in Prio3.) This is the same value that would be transmitted during preparation of Prio3.

Now, in DAP, the Helper's report share is proxied by the Leader during aggregation. Thus, one verifier share per-report is transmitted either in a traditional aggregation job via Prio3 or a batched aggregation job via Whisper. The only difference is who generates the message.

Whisper would only make a difference in a "Split-Upload" architecture, where each Client sends report shares to the Leader and Helper directly. In this setting, the Clients pay the bandwidth cost, rather than the Leader. It has been observed (#130) that bandwidth is usually cheaper for Clients than it would be for a Leader. Note that [we ruled out Split-Upload for DAP at IETF 113](https://datatracker.ietf.org/meeting/113/materials/slides-113-ppm-ppm-upload-flow).

All that said, we may see improvements to Whisper in the future that make it worth it for DAP as-is. And there are other VDAFs that may fair better. For example, [VIDPFs](https://eprint.iacr.org/2023/080) not only allow for batched preparation, but also reduce Client->Aggregator bandwidth[^1].


[^1]: There is a big caveat here: The parameters of VIDPF are subject to change as we learn more about their concrete security.

**Comment by cjpatton** [comment]
This topic was brought up at IETF 120: https://datatracker.ietf.org/meeting/120/materials/slides-120-ppm-batched-vdaf-preparation

There wasn't much enthusiasm for this feature in the room. In any case, there is no point in supporting it in DAP unless we're willing to re-consider the Split-Upload architecture.

**Comment by mayank0403** [comment]
Hi, 

I co-authored the [Whisper](https://eprint.iacr.org/2024/666) paper and thanks to everyone for showing interest in the work!

I think a small change in the construction of silently verifiable proofs would fix the issue mentioned above. The idea is that the public proof doesn't need to be sent to the helper; as long as the leader has it, that's enough. 

Report shares would look like this:
Leader gets: measurement share, prio3 proof share, public proof
Helper gets: measurement seed, prio3 proof seed, one extra seed for Fiat-Shamir

With this change, even when the leader relays Helper's report shares, the leader's egress stays very low (512 bits egress per report - includes egress during proof verification).

Please refer to the attached document for a formal description. Note that the document's exposition is simplified by considering only Prio3 proofs, but any proofs that we talk about in our paper will work here. 

I am curious to hear your thoughts! 
[Whisper_IETF_Draft.pdf](https://github.com/user-attachments/files/16567347/Whisper_IETF_Draft.pdf)

**Comment by cjpatton** [comment]
Hi @mayank0403, thanks so much for correcting the record here! Quick question about the batched verification step: a collision hash function is used to compute the tag for each report; how then are the tags batched? My recollection from the paper is that the tags are field elements, and we take a random linear combination of the tags to get the batched tag. I guess the same thing works here if the range of the hash function is the field: is that your suggestion here?

**Comment by cjpatton** [comment]
We don't have clear consensus to add support for batched preparation to DAP right now. It's also been pointed out that this feature can be added to DAP relatively easily by a future draft (see for example #565). As we're getting close to feature freeze for this draft, I'm going to go ahead and close this issue.
