### ISSUE TITLE
Clarification request: Does aggregation happen in the AggregationJob?

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-ppm/draft-ietf-ppm-dap#571]
Section 4.5 says that an Aggregation Job has three phases, the last of which is

>    *  Completion: Finish the aggregate flow, yielding an output share
      corresponding to each report share in the aggregation job.

That makes it sound like Aggregation Jobs don't perform any aggregation.  If that's true, maybe they should be called Preparation Jobs.  If it's false, maybe it can be corrected.

**Comment by cjpatton** [comment]
It's false: we leave it up to an implementation to decide whether it will store output shares individually or aggregate in a streaming fashion (once an output share is produced, add it to an aggregate share).

A bit of pertinent history: Early on we wanted to allow the possibility that the aggregation function (i.e., the function computed by the VDAF) may be sensitive to the order of measurements. For example, you might have that $f(m_1, m_2, m_3) \ne f(m_1, m_3, m_2)$. The VDAF draft doesn't rule this out, but in practice we have not found a need for this. In fact, no open source implementation of DAP that I'm aware of supports it.

I think we can resolve this by clarifying that most of the time the aggregate share will usually be updated in a streaming fashion. (Thanks @bemasc for suggesting the terminology offline.)

**Comment by cjpatton** [comment]
@bemasc there's an implementation note in {{collect-flow}} that describes streaming aggregation, but this is pretty buried. PR #580 defines this term in the overview for {{agg-flow}}. It also clarifies that future batch modes may be incompatible with this feature.

**Comment by bemasc** [comment]
It seems like there are still some open questions here about terminology.

**Comment by cjpatton** [comment]
As discussed offline: we resolved this in #580 by clarifying in the overview that we will usually do streaming aggregation. On the PR we discussed the possibility of strengthening this by making streaming aggregation normative text rather than an implementation detail.

If we don't end up doing this, then let's rename "aggregation job" to "preparation job" as you suggest.
