### ISSUE TITLE
Consider adding task start time

### ISSUE THREAD

**Issue by junyechen1996** [ietf-wg-ppm/draft-ietf-ppm-dap#606]
Initially brought up by @cjpatton in https://github.com/wangshan/draft-wang-ppm-dap-taskprov/issues/62.

It may make sense to introduce the concept of it in the base DAP draft as well. We can use this parameter to enforce things like:
- Task lifetime is not too long.
- Report timestamp should not be before the task start time.

**Comment by cjpatton** [comment]
2024/10/9 dap sync: why not just record the time stamp? Clock skew between leader and helper might make them reject reports differnently.
