### ISSUE TITLE
Align spec with ACME (was "Version all API endpoints")

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#61]
The protocol doc specifies HTTP endpoints like `[leader]/upload_start` or `[helper]/key_config`. We should make sure to insert a protocol version in the endpoints so that we can iterate on this in the future. i.e., `[leader]/v1/upload_start`.

**Comment by cjpatton** [comment]
I was thinking the same thing :)

In fact, we might always include the version and task id in the request URI. For example:

example.com/[version]/[task_id]/upload_start

**Comment by ekr** [comment]
I don't believe that this is considered current best practice. See, rather,
the structure used by ACME:

https://tools.ietf.org/rfcmarkup?doc=8555#section-7.1

**Comment by martinthomson** [comment]
I don't know if this is recorded anywhere, but that is a bad way to version APIs.  Mostly because it is unnecessary.  Just change the `[leader]` part to something different.  Our services team has a simple policy: if you are going to make an incompatible change,  spin up an entirely new endpoint on a new domain name.  Compatible changes (new request or response formats for example) can use content negotiation.  And generally we use extensible formats (like JSON) that allow you to add protocol elements in a consistent fashion that result in predictable outcomes.

**Comment by cjpatton** [comment]
The reason to do this is not just about versioning, since we also want to specify a "task id" for the request.

**Comment by ekr** [comment]
On Wed, Jun 23, 2021 at 2:59 PM Christopher Patton ***@***.***>
wrote:

> The reason to do this is not just about versioning, since we also want to
> specify a "task id" for the request.
>

I'm not following how that changes the situation. Can you expand?

**Comment by cjpatton** [comment]
I'm responding to @martinthomson's comment that the URI should not encode the version. I'm fine with that, I'm just not sure how to structure the request in a way that conveys the task id as well as the version. (I haven't yet looked at your link to the ACME spec, but I will)

**Comment by martinthomson** [comment]
If the goal is to ensure that a client is able to communicate specific information to a server, in HTTP that's something we use headers for sometimes, but mostly it is what the content of a request is for.  I imagine here that we're talking about posting a bunch of stuff to a server, so there will be a payload into which you can put lots of goodies.

The message content might include a version, but versioning for content can and should use media types instead.  That too doesn't directly need an explicit version (not `application/my-protocol-v1` or far worse `application/my-protocol;v=1`), you just use a media type to ensure that if the client wants to send something else, the server won't get confused.

In practice, if you need to make a breaking change, it's better to do that at the level of URI (as stated earlier).  You might also make new content types at the same time, which is good practice, but the primary thing that stops things from going badly is the entirely new endpoint that you talk to.

**Comment by cjpatton** [comment]
Another thing to consider here (came up in the 2021/7/14 call): Responding to requests may take some time:
1. Collect requests are blocked until the batch is saturated
2. In Hits, each collect request is blocked until the previous requests is finished.

@ekr mentioned that ACME has a way of dealing with this.

**Comment by martinthomson** [comment]
ACME effectively uses what you might call a "transaction resource" for this purpose.  When a request is made, the response does not answer that request, but instead provides an link to an alternative resource from which the answer will eventually be available.  Clients then poll that resource to learn when their certificate is ready.  For the stated reasons, this is probably necessary here also.

**Comment by tgeoghegan** [comment]
I am closing this issue because I don't think there's any action to take here in DAP: we're not going to do in-band protocol versioning for the reasons Martin laid out above, and I don't think there's anything else from ACME we want to borrow.
