### ISSUE TITLE
Rejecting reports outside the task's validity window

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#625]
[Rejecting reports with timestamps larger than the task expiration date is optional](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/13c7e905c12fa2b2460f2a18f8b6a39ab53472ac/draft-ietf-ppm-dap.md?plain=1#L1870-L1872):

> Check if the report's timestamp has passed the task's `task_expiration` time.
> If so, the Aggregator MAY mark the input share as invalid with the error
> `task_expired`.

Likewise for #624, which adds a task start time.

Should this MAY be a MUST? It's easy enough for each Aggregator to enforce, since it just has to compare the timestamp reported by the client to the expiration date associated with the task. (The Aggregator doesn't need to check what time it is, for example.)

Rejecting reports that fall outside the task validity window seems like a good idea because it reduces the amount of time the VDAF verification key is in use.

I did some `git blame` splunking and traced this to the following PR from @wangshan: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/304. We didn't discuss this much, and based on the conversation on the linked issue, it sounds like it wasn't really our highest priority. Our top line concern was making sure the Aggregators know when they can clean up their storage.

**Comment by branlwyd** [comment]
I support turning this `MAY` into a `MUST`.

**Comment by cjpatton** [comment]
2024/10/24 interim: I think we failed to talk this one out, but I suspect this won't be a controversial change. I'll put up a PR and wait a week for feedback.
