### ISSUE TITLE
Make task start time & end time both optional.

### ISSUE THREAD

**Issue by branlwyd** [ietf-wg-ppm/draft-ietf-ppm-dap#634]
Currently, tasks have two parameters specifying the time interval in which the task is "valid": `task_start` and `task_duration`. Since the end time of the task is determined by `task_start + task_duration`, if the task has and end time it must also have a start time.

I think it would be better if both the start & end times were, independently, optional. So a task could have neither, either, or both of these parameters specified.

One way to do this would be to directly specify `task_start` and `task_end`, and specify that these parameters are optional. I believe we avoided specifying things this way previously to avoid a validity check (`task_end >= task_start`), but IMO allowing these parameters to be optional is more important.

**Comment by cjpatton** [comment]
There are security considerations that are relevant here, like over exposing the VDAF verification key, so I think we'd have to a pretty good reason to do this. What use case(s) do you have in mind for this?

**Comment by cjpatton** [comment]
@branlwyd can we close?

**Comment by branlwyd** [comment]
I think we can close: implementations are free to implement `task_start` & `task_end` rather than `task_start` & `duration` if they so choose, and this implementation strategy is compatible (in the sense that the implementation can convert as-needed).
