### ISSUE TITLE
Multiple helpers (was "Should multipler helpers be baked into the core protocol?")

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#68]
The reason for having multiple helpers is to (partially) recover the protocol output in case a helper goes offline. (See #4.) We currently bake this into the protocol by associating a set of helper URLs with the PPM parameters. This complicates the protocol in two ways:
1. When uploading reports, the client has to pick the set of helpers it will upload reports for (see #50).
2. When collecting outputs (see #59), the collector has to specify which helper the leader will engage with.

When reviewing #59, @chris-wood pointed out that we can simplify the protocol by having one helper per task. If deployments want to add redundancy, they can do so by spinning up more tasks with identical parameter except with a different helper for each task.

**Comment by ekr** [comment]
I don't think that high availability is a good reason to allow for multiple helpers. If you want HA, stand up multiple instances in different data centers, etc.

The reason to allow for multiple helpers is to provide a higher level of assurance, namely to require >2 entities to collude in order to violate user privacy. It might be that we could defer that, though it's not clear to me why a fixed set of 2 helpers is more complicated than a fixed set of 1 helper.

WRT #50 I don't think that the leader should e telling the client about helpers at all. See #65

**Comment by cjpatton** [comment]
> I don't think that high availability is a good reason to allow for multiple helpers. If you want HA, stand up multiple instances in different data centers, etc.

When we discussed this last we agreed that multiple helpers would be used for resiliency and not for weakening the trust model. Making this change at this point is fine, but I just want to note that it's a course correction and want to make sure we're all on the same page about.

> The reason to allow for multiple helpers is to provide a higher level of assurance, namely to require >2 entities to collude in order to violate user privacy. It might be that we could defer that, though it's not clear to me why a fixed set of 2 helpers is more complicated than a fixed set of 1 helper.

There are two ways in which this complicates things:

1. Not every PA protocol is well-defined for more than one helper. In particular, heavy hitters, as specified in [1], is defined for exactly two servers (one leader and one helper).
2. Input validation gets more complicated. For Prio, the leader will have to make a request to each helper, combine the results and make the validity decision, then make a second request to each helper in order to disseminate the decision. Right now Prio can be implemented with just one request to the helper.

With these wrinkles in mind, I'd be in favor of allowing multiple helpers to be used this way.

[1] https://eprint.iacr.org/2021/017

**Comment by ekr** [comment]
> > I don't think that high availability is a good reason to allow for multiple helpers. If you want HA, stand up multiple instances in different data centers, etc.
> 
> When we discussed this last we agreed that multiple helpers would be used for resiliency and not for weakening the trust model. Making this change at this point is fine, but I just want to note that it's a course correction and want to make sure we're all on the same page about.

Well, at this non-WG stage of the process "we" and "agreed" are necessarily kind of fuzzy. so I think there's really a presumption that there's a high bar to make changes. In any case, I don't recall being part of that discussion, so what was the rationale for this? Remember, we're not talking about multiple machines here but rather multiple operators. Is there some reason that ISRG is the leader and Cloudflare is the helper that the system needs to survive a Cloudflare outage? It seems like we've got bigger problems in that case. And note that the system as specified won't survive an outage at the leader.

> 
> > The reason to allow for multiple helpers is to provide a higher level of assurance, namely to require >2 entities to collude in order to violate user privacy. It might be that we could defer that, though it's not clear to me why a fixed set of 2 helpers is more complicated than a fixed set of 1 helper.
> 
> There are two ways in which this complicates things:
> 
>     1. Not every PA protocol is well-defined for more than one helper. In particular, heavy hitters, as specified in [1], is defined for exactly two servers (one leader and one helper).
> 
>     2. Input validation gets more complicated. For Prio, the leader will have to make a request to each helper, combine the results and make the validity decision, then make a second request to each helper in order to disseminate the decision. Right now Prio can be implemented with just one request to the helper.
> 
> 
> With these wrinkles in mind, I'd be in favor of allowing multiple helpers to be used this way.

Well, I'm certainly open to having only one helper, if that makes things much easier; I'm just saying that that's the only reason  I am aware of for having > 1
> 
> [1] https://eprint.iacr.org/2021/017

**Comment by cjpatton** [comment]
> Well, at this non-WG stage of the process "we" and "agreed" are necessarily kind of fuzzy. so I think there's really a presumption that there's a high bar to make changes.

By "we" I mean the folks who were on the call when we discussed it and who have chimed in on issues and PRs. Yes, this is necessarily fuzzy and subject to change.

> In any case, I don't recall being part of that discussion, so what was the rationale for this? Remember, we're not talking about multiple machines here but rather multiple operators. Is there some reason that ISRG is the leader and Cloudflare is the helper that the system needs to survive a Cloudflare outage? It seems like we've got bigger problems in that case. And note that the system as specified won't survive an outage at the leader.

No, we were thinking more of a scenario where the leader is a well-provisioned service provider, like ISRG or Cloudflare, and the helper is a dinky third-party that fails to handle a sudden load spike.

**Comment by ekr** [comment]
> No, we were thinking more of a scenario where the leader is a well-provisioned service provider, like ISRG or Cloudflare, and the helper is a dinky third-party that fails to handle a sudden load spike.

I think this is a case of "don't do that then"

**Comment by cjpatton** [comment]
The only way I would push back is that requiring that everyone be on a cloud service means there's less diversity in where secret shares are going. If they're going to service providers on the same infrastructure (GCP, say), I could argue that this isn't adding much to privacy.

**Comment by ekr** [comment]
Sure, but I think one deals with that by having the Collector retry.

**Comment by cjpatton** [comment]
Well, you're not going to be able to solve every problem this way. It's easy to imagine a helper getting into a state in which the output can't be recovered for a batch. (As a simple example, suppose the helper forgets its key.)

**Comment by ekr** [comment]
> Well, you're not going to be able to solve every problem this way. It's easy to imagine a helper getting into a state in which the output can't be recovered for a batch. (As a simple example, suppose the helper forgets its key.)

Well, now we're not talking about load spikes but about something different.


> But getting back to the original issue: if you want to add redundancy, you can do so without the details of how you do it bleeding into the protocol. I'm fine with that. But we do need to make a decision on the scope of a task.

I don't know what you mean here. Can you elaborate?

**Comment by cjpatton** [comment]
> > Well, you're not going to be able to solve every problem this way. It's easy to imagine a helper getting into a state in which the output can't be recovered for a batch. (As a simple example, suppose the helper forgets its key.)
> 
> Well, now we're not talking about load spikes but about something different.

That's just an example. My larger point is that we should lower the bar to entry wherever possible. And to re-iterate, this was the original intention of multiple helpers. (Personally, I'm open to changing this requirement.)

> > But getting back to the original issue: if you want to add redundancy, you can do so without the details of how you do it bleeding into the protocol. I'm fine with that. But we do need to make a decision on the scope of a task.
> 
> I don't know what you mean here. Can you elaborate?

If we change the spec so that there's just one helper per PAParam, then adding another helper (for redundancy) would require distributing another PAParam. That's fine, except that right now we're assuming a 1:1 correspondence between PATask and PAParam.

**Comment by ekr** [comment]
> That's just an example. My larger point is that we should lower the bar to entry wherever possible.

I would say "where practical". 

> And to re-iterate, this was the original intention of multiple helpers. (Personally, I'm open to changing this requirement.)

OK. Well, perhaps we should press pause on this discussion and see what others say.



> If we change the spec so that there's just one helper per PAParam, then adding another helper (for redundancy) would require distributing another PAParam. That's fine, except that right now we're assuming a 1:1 correspondence between PATask and PAParam.

Well, this is more of a topic for #65. But I don't see a problem with having multiple task IDs for the same logical operation with different helpers. That seems a lot simpler in general and in specific pushes complexity out from the main system into the collector/clients, which, as noted in #65, have an arbitrarily rich channel that we don't need to standardize.

**Comment by cjpatton** [comment]
Just want to cross-reference this comment here: https://github.com/abetterinternet/prio-documents/pull/70#pullrequestreview-703109761

**Comment by cjpatton** [comment]
What's left for this issue is to decide if/how to allow for multiple helpers for privacy.

**Comment by tgeoghegan** [comment]
We discussed the question of multiple helpers at [IETF 116](https://datatracker.ietf.org/meeting/116/materials/agenda-116-ppm-03) and [on the mailing list](https://mailarchive.ietf.org/arch/msg/ppm/TnAYiud5OVlQNfUv71BM6Tl6tNs/). The consensus we arrived at is that we want to specialize DAP for exactly 2 aggregators for simplicity and to enable [performance gains](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/393). I don't think there's anything else to do in this issue, so I'm closing it.
