### ISSUE TITLE
Discuss client attestation in security considerations

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#89]
Many deployments will be in a position to have clients attest that (1) the report was generated by a trusted client or (2) the report was generated within a trusted execution environment. (1) allows you to mitigate Sybil attacks by only consuming reports generated by trusted clients (#86, #20). On top of that, with (2) you might choose to forego expensive MPC for validating inputs altogether (#45). We don't want to require these features for all deployments, but they're useful enough that we should make sure our protocol accommodates them.

With that in mind, it would be useful if folks that plan to do this would provide some details about how they envision composing (1) or (2) with PDA**. The question to answer is what changes, if any, are needed for the core spec.

cc/ @tgeoghegan, @csharrison, and @hostirosti

** 2022/1/18: Note that "PDA" was the working name for the PPM protocol at the time this issue was initially discussed.

**Comment by csharrison** [comment]
For our use-case we were thinking of something like [Privacy Pass](https://datatracker.ietf.org/wg/privacypass/documents/) for anonymous attestation. However, this was in the context of a collector / proxy sitting between the client and the leader who is responsible for issuing and redeeming tokens. This design would put all attestation outside of the PDA protocol, and allow the collector to determine which clients are trusted. However, it only benefits the collector which has a different set of requirements from the PDA system.

Collectors want to make sure their data is accurate. The PDA system wants to ensure privacy. To that end I could imagine two layers of attestation:
1. A layer of attestation that records are trusted by the collector
2. A layer of attestation that records are trusted by PDA

However, I don't have any concrete ideas on how to accomplish (2) for our use-case realistically.

**Comment by cjpatton** [comment]
> For our use-case we were thinking of something like [Privacy Pass](https://datatracker.ietf.org/wg/privacypass/documents/) for anonymous attestation. However, this was in the context of a collector / proxy sitting between the client and the leader who is responsible for issuing and redeeming tokens. This design would put all attestation outside of the PDA protocol, and allow the collector to determine which clients are trusted. 

This batched upload idea is still on the table, I think: see https://github.com/abetterinternet/prio-documents/issues/64. In particular, I think we're all in agreement that some collector/proxy should be able to opaquely carry out some client attestation thing and upload only "trusted" reports to the leader. (@tgeoghegan calls this the "ingestor, I believe.) The problem, as you point out, is the trust relationship between the leader and uploader.

> Collectors want to make sure their data is accurate. The PDA system wants to ensure privacy. To that end I could imagine two layers of attestation:
> 
>     1. A layer of attestation that records are trusted by the collector
> 
>     2. A layer of attestation that records are trusted by PDA
> 
> 
> However, I don't have any concrete ideas on how to accomplish (2) for our use-case realistically.

Yeah, it's not clear to me either what the best thing would be here. As a strawman, consider having the uploader sign the set of reports and have the aggregators verify the signature. If the uploader *is* the collector, then this scheme implies a trust relationship between the collector and at least one aggregator. (In particular, the adversary could still do a Sybil attack.) For this to work, you'd want there to be some sort of organizational separation between the collector and uploader.

**Comment by chris-wood** [comment]
Taking a step back, why do we need any sort of attestation _in this protocol_? Both (1) and (2) seem very deployment specific to me. In particular, if Sybil attacks are out of scope for the core protocol, then surely they should be addressed _outside_ of the core protocol, right? One can add attestation via Privacy Pass or whatever in the protocol that wraps PDA.

**Comment by cjpatton** [comment]
Ideally yes, but the question we're asking here is whether one would need to change our spec in order to accommodate a mechanism for (1) or (2).

**Comment by ekr** [comment]
This seems like a great case for an extensible protocol, or as @chris-wood  suggests, a wrapper protocol.

I think it's clear that one can have a PDA MVP without this.

**Comment by cjpatton** [comment]
Looks like the consensus is to park this.

**Comment by tgeoghegan** [comment]
Way back in DAP-02 (https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/305), we agreed to push request authentication out of the DAP protocol, on the premise that implementations and deployments are better positioned to make these choices than DAP is. I think the same is true of request attestation, especially if we think of attestation as being a feature of an authentication scheme.

At most, we should discuss in security considerations how client auth and attestation can help mitigate Sybil attacks. I'm repurposing this issue for that objective and we'll deal with it in the scope of #460.

**Comment by divergentdave** [comment]
This is addressed in the recent security considerations rewrite, under [section 7.2.1, Client authentication](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-client-authentication).
